style: create modal container
momentum-design/momentum-design pull request #1007
Opened 2024-12-20 20:16 UTC by Jason20020

# Description

- Create Modal Container
## Links

_Please replace this line with relevant links to the changes made in this Pull Request._

2025-01-17 12:25 UTC, supminn requested changes

2025-01-17 12:25 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.component.ts
> +   * Elevation of the modalcontainer
suggestion: a brief explanation and what each value of elevation would do and the different values available.

2025-01-17 12:25 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.component.ts
> +  override ariaLabel: string | null = null;
question: why is it set to `null`? since aria-label is a string, we could set the default value to an empty string ''

2025-01-17 12:25 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.component.ts
> +        class='modal-container'
```suggestion
        id='mdc-modal-container' 
        class='mdc-modal-container'  
```

2025-01-17 12:25 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.stories.ts
> +      description: 'Provides an accessible name for the modal.',
suggestion: This description can be moved into tsdocs of the component. This instance can be omitted.

2025-01-17 12:25 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.styles.ts
> +      border: 0.0625rem solid var(--mdc-modalcontainer-inverted-border-color);
nitpick: since the border width and style is the same as above(line 23), we could change only the color as 
`border-color: var(--mdc-modalcontainer-inverted-border-color)`

2025-01-17 12:25 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.e2e-test.ts
> +        aria-label="avatar button"
issue: aria-label value is incorrect

2025-01-17 12:25 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.e2e-test.ts
> +
suggestion: You could replace `test` with `test.steps` as each `test` block pertains to create a new instance of the components page which leads to performance drop

2025-01-17 12:25 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.e2e-test.ts
> +    await componentsPage.accessibility.checkForA11yViolations('modalcontainer-default');
suggestion: You could run A11y on the stickersheet too. It would test for all the variants of the component at once.

2025-01-17 14:35 UTC, cscheffauer commented on packages/components/src/components/modalcontainer/modalcontainer.component.ts
> +  override ariaLabel: string | null = null;
i would recommend to be careful with this - aria-label should either be set or not on the element at all, we should avoid a `<mdc-modalcontainer aria-label ../>` at all costs, cause automated accessibility testing might consider this to "pass", where the aria-label is actually not correctly set. please check whats the right way to remove the aria-label completely in the DOM tree.

2025-01-20 12:29 UTC, supminn requested changes

2025-01-20 12:29 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.component.ts
> +  override role: string = DEFAULTS.ROLE;
suggestion: we need to restrict the role to `dialog` and `alertdialog`. We can create a TS type to support the 2 roles.
Currently, it is of the type string, hence we get the following issue.

<img width="812" alt="image" src="https://github.com/user-attachments/assets/e039420b-edfd-4d4f-ae0e-ee6abb9f9167" />

2025-01-20 12:29 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.component.ts
> +        aria-modal=${this.ariaModal}
```suggestion

  public override render() {
    return html`
      <div 
        id='mdc-modal-container' 
        class='mdc-modal-container'  
        ?contrast="${this.color === 'contrast'}"
        role="${this.role}"
        aria-modal="true"
```

https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-modal

aria-modal is relevant only on dialog and alertdialog containers. We could force set them to true since the modal container could have either of these 2 roles.

2025-01-20 12:29 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.e2e-test.ts
> +        aria-model="dialog"
This is no longer required with the above mentioned changes.

2025-01-20 12:29 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.stories.ts
> +  aria-modal="${args['aria-modal']}"
same as above. This is not required.

2025-01-20 12:29 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.component.ts
> +        aria-label=${ifDefined(this.ariaLabel)}
```suggestion
        aria-label=${ifDefined(this.ariaLabel) as string}
```

Adding a type assertion to fix the issue.

2025-01-21 07:28 UTC, supminn requested changes

2025-01-21 07:28 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.stories.ts
> +  <mdc-text>Lorem ipsum dolor sit amet.</mdc-text>
question: We should set this as a part of children right?

2025-01-21 07:28 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.component.ts
> + *
suggestion: Can we add tsdoc info about `children` here.
The contents of modal container is considered with the default slot.

2025-01-21 07:28 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.stories.ts
> +    },
issue: update this with the available role options.
suggestion: you could use a radio option here.

2025-01-21 07:28 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.e2e-test.ts
> +};
```suggestion
type SetupOptions = {
  componentsPage: ComponentsPage;
  color?: ModalContainerColor;
  elevation?: ModalContainerElevation;
  role?: ModalContainerRole;
  children?: string;
};
```

2025-01-21 07:28 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.e2e-test.ts
> +        role="dialog"
```suggestion
       ${restArgs.role ? `role="${restArgs.role}"` : ''}
```

2025-01-21 07:28 UTC, supminn commented on packages/components/src/components/modalcontainer/modalcontainer.e2e-test.ts
> +    }
suggestion: Test step for checking the role of the modal container could be added here.

2025-01-22 12:24 UTC, supminn approved these changes

2025-01-22 12:26 UTC, merged