refactor: avatarButton component created using AvatarMixin and Buttonsimple
momentum-design/momentum-design pull request #1009
Opened 2024-12-23 08:21 UTC by supminn

# Description

Refactoring https://github.com/momentum-design/momentum-design/pull/999 to use buttonsimple component (created in -https://github.com/momentum-design/momentum-design/pull/1008)
This PR creates a new component avatarButton that is -

- Built as a clickable avatar with buttonsimple as a wrapper.
- This button avatar component uses the same attributes which are used in avatar component.
- All of the business logic will be the same for Avatar and this component.
- Create a new mixin: AvatarComponentMixin to inherit common props in between both Avatar and ButtonAvatar components.

![image](https://github.com/user-attachments/assets/0f0e0a6b-0c80-4c3d-89bc-6792edc31173)

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-461

2025-01-06 16:20 UTC, arjunkesava requested changes

2025-01-06 16:20 UTC, arjunkesava commented on packages/components/src/components/avatarbutton/avatarbutton.component.ts
> +import { AvatarSize } from '../avatar/avatar.types';
```suggestion
import type { AvatarSize } from '../avatar/avatar.types';
```

2025-01-06 16:20 UTC, arjunkesava commented on packages/components/src/utils/mixins/DisabledMixin.ts
> +import { Constructor } from './index.types';
```suggestion
import type { Constructor } from './index.types';
```

2025-01-06 16:20 UTC, arjunkesava commented on packages/components/src/utils/mixins/TabIndexMixin.ts
> +import { Constructor } from './index.types';
```suggestion
import type { Constructor } from './index.types';
```

2025-01-07 11:45 UTC, arjunkesava commented on packages/components/src/utils/mixins/AvatarComponentMixin.ts
> +     * The maximum number is 99 and if the give number is greater than 99,
```suggestion
     * The maximum number is 99 and if the given number is greater than 99,
```

2025-01-07 11:45 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.utils.ts
> +import { PresenceSize } from '../presence/presence.types';
```suggestion
import type { PresenceSize } from '../presence/presence.types';
```

2025-01-07 12:43 UTC, arjunkesava commented on packages/components/src/components/avatarbutton/avatarbutton.stories.ts
> +      'avatarSize',
As we've moved from Button to SimpleButton component, we can remove the props which were not defined at all.

```suggestion
      'active',
      'disabled',
      'soft-disabled',
      'tabIndex',
      'role',
      'type',
```

2025-01-07 12:54 UTC, supminn commented on packages/components/src/components/avatarbutton/avatarbutton.component.ts
> +  constructor() {
that's right.
However, we are not making any changes or modification to this property. Thus, we do not need to override it.
The consumer would add pass aria-label value and it would automatically reflect on the component.

2025-01-08 05:39 UTC, arjunkesava approved these changes
LGTM.

2025-01-08 05:39 UTC, merged