Feat/docs/add initial project
momentum-design/momentum-design pull request #150
Opened 2022-11-22 18:28 UTC by torgeadelin

# Description

Added docs project structure + tokens docs.
Most of the code is boilerplate.

Most code I added  is under `pages/tokens`
## Links

Demo: http://10.209.86.40:3000/

2022-11-22 19:11 UTC, torgeadelin commented
Things left to do:
- update the plop generated files to reflect the correct scripts 
- maybe figure out a way to automatically generate the token pages
- add build in the pipeline process and publish to github pages
- grab all the API references generated by api-extractor and add them to the docs.

2022-11-23 02:07 UTC, chrisadubois approved these changes
saw your comments on the PR, that would be good to do

requirement is for sure not to store the built code on /docs but to build it via github actions and deploy to the docs branch every time a merge occurs

requirement is also to add automation for the token pages (should not be manual as the designers are automated)

else than that -- I think the cat gif is funny, but we should probably not have that screen there

2022-11-23 14:29 UTC, InteractiveTimmy requested changes
review of just `docs.yaml`. Rename this file extension to `yml` if you can.

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +      - name: Detect package manager
Use `actions/node` instead, as it does a check similar to this:

```
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'
```

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +        uses: actions/checkout@v3
new line after step completion:

```
steps:
  - name: Checkout
  - uses: actions/checkout@v3
  
  - name: ...
```

style suggestion: needed for all steps in this file

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +      - name: Install dependencies
Suggestion: This could be an initialization job:

```
      - name: Validate Dependencies
        id: validate-dependencies
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install Dependencies
        if: steps.validate-dependencies.outputs.cache-hit != 'true'
        run: yarn

      - name: Cache Dependencies
        uses: actions/cache@v3
        if: steps.validate-dependencies.outputs.cache-hit != 'true'
        with:
          path: '**/node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
```

See: .github/workflows/deploy-package.yml

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +concurrency:
not sure if concurrency is needed, is there a reason for this?

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +name: Deploy Astro site to Pages
This *could* exist in the `deploy-package.yml` file, unless the intent is to have this run via manual trigger, in this case, add `workflow_dispatch:` to your `on` clause

```
on:
  push:
    branches:
      - main
  workflow_dispatch:
```

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +    branches: ["main"]
recommendation:

```
on:
  push:
    branches:
      - main
  workflow_dispatch:
```

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +  BUILD_PATH: "." # default value when not using subfolders
Question: Assuming this allows for astro to build to the project root dir?

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +        uses: actions/setup-node@v3
This one makes the above check redundant, doesn't it?

2022-11-23 14:29 UTC, InteractiveTimmy commented on .github/workflows/docs.yaml
> +        uses: actions/upload-pages-artifact@v1
Is this needed with the below step? This is likely correct, but I'm curious as to if `@actions/deploy-pages` does this already.

2022-11-23 14:39 UTC, chrisadubois commented on .github/workflows/docs.yaml
> +      - name: Install dependencies
i actually dont think we need this file at all?

2022-11-23 16:26 UTC, torgeadelin commented on .github/workflows/docs.yaml
> +      - name: Detect package manager
refactored

2022-11-23 16:31 UTC, torgeadelin commented on .github/workflows/docs.yaml
> +      - name: Install dependencies
refactored

2022-11-23 16:33 UTC, torgeadelin commented on .github/workflows/docs.yaml
> +name: Deploy Astro site to Pages
hmm, I'm not sure what the best thing to do is. maybe we leave it as separate flow to make everything more decoupled?

2022-11-23 16:34 UTC, torgeadelin commented on .github/workflows/docs.yaml
> +  BUILD_PATH: "." # default value when not using subfolders
I think that's what this is for, yes. 
I used a template to create this workflow.

2022-11-23 20:31 UTC, InteractiveTimmy approved these changes
LGTM, @chrisadubois , could you take a quick look at this PR?

2022-11-24 11:58 UTC, merged