Theme token updates
momentum-design/momentum-design pull request #178
Opened 2022-12-02 07:36 UTC by seheekim1009

Theme & common token updates
- Moved 9 Illustration colors into common tokens as they have the same value.
- Moved illustration under "content" tokens. 
- Fixed some descriptions for consistency between dark & light modes. 

Ready for review ;)

2022-12-05 13:17 UTC, nataliadelmar requested changes

2022-12-05 13:17 UTC, nataliadelmar commented on packages/@momentum-design/tokens/src/core/border-radius.json
> +      "description": "Small border radius.\nbuttz"
did you intend to add this to the description?

2022-12-05 13:17 UTC, nataliadelmar commented on packages/@momentum-design/tokens/src/theme/webex/common.json
> +            "01-copy": {
you got a 01-copy here that Im sure you didn't mean to have :)

2022-12-06 15:27 UTC, seheekim1009 commented on packages/@momentum-design/tokens/src/core/border-radius.json
> +      "description": "Small border radius.\nbuttz"
Ask Trip. I assume this means button!

2022-12-06 20:00 UTC, merged