Design token updates
momentum-design/momentum-design pull request #274
Opened 2023-01-31 21:31 UTC by seheekim1009

Updated HEX Values of Orange Core Color Tokens to fix the accessibility bug reported by the Realtime team.
Ready for review ;)

2023-01-31 22:18 UTC, nataliadelmar requested changes

2023-01-31 22:18 UTC, nataliadelmar commented on packages/@momentum-design/tokens/src/theme/webex/border-radius.json
> +    "theme": {
we need to add "core" layer to the core border-radius. This is to differentiate theme from core border-radius tokens.

2023-01-31 22:18 UTC, nataliadelmar commented on packages/@momentum-design/tokens/src/theme/webex/border-width.json
> +  "border-radius": {
did you mean border-width?

2023-01-31 22:18 UTC, nataliadelmar commented on packages/@momentum-design/tokens/src/theme/webex/border-width.json
> +    "theme": {
same here, we need to add "core" layer to the core border-width. This is to differentiate theme from core border-width tokens.

2023-01-31 22:18 UTC, nataliadelmar commented on packages/@momentum-design/tokens/src/theme/webex/elevation.json
> +    "theme": {
same here :) we need to add "core" layer to the core elevation tokens. This is to differentiate theme from core elevation tokens.

2023-01-31 22:18 UTC, nataliadelmar commented on packages/@momentum-design/tokens/src/theme/webex/spacing.json
> +    "theme": {
same here :) we need to add "core" layer to the core spacing tokens. This is to differentiate theme from core spacing tokens.

2023-01-31 22:27 UTC, chrisadubois commented on packages/@momentum-design/tokens/src/theme/webex/border-width.json
> +    "theme": {
did you mean border-width?

2023-01-31 22:40 UTC, seheekim1009 commented on packages/@momentum-design/tokens/src/theme/webex/spacing.json
> +    "theme": {
@tricarro Can you check this out? I think the push you did last Dec wasn't merged yet, got caught while I'm updating core colors.

2023-02-01 19:52 UTC, tricarro commented on packages/@momentum-design/tokens/src/theme/webex/border-width.json
> +  "border-radius": {
I just fixed this Natlia.

2023-02-01 19:54 UTC, tricarro commented on packages/@momentum-design/tokens/src/theme/webex/border-radius.json
> +    "theme": {
Aren't these already differentiated? There's a Core set of tokens "[packages/@momentum-design/tokens/src/core]" and a theme set "[packages/@momentum-design/tokens/src/theme]".

Or, am I understanding the set up incorrectly?

2023-02-06 13:20 UTC, nataliadelmar approved these changes

2023-02-06 16:50 UTC, nataliadelmar approved these changes

2023-02-06 16:55 UTC, merged