feat: g tag detector implementation
momentum-design/momentum-design pull request #507
Opened 2024-02-01 09:42 UTC by gnanammcp

# Description

Adding the <g> tag detector function to Figma plugin

## Links

Adding the <g> tag detector function to Figma plugin

2024-02-08 09:14 UTC, cscheffauer requested changes

2024-02-08 09:14 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.css
> +  background-color: rgb(0, 0, 0);
please use figma color variables here instead, since there is an issue when you open Figma in dark mode, see here:
![image](https://github.com/momentum-design/momentum-design/assets/29776408/79a44842-231f-4e92-9935-4d3ee2a584bf)
I would recommend to make the background color of this modal content black and a grey border or something. See colors here: https://www.figma.com/plugin-docs/css-variables/#semantic-color-tokens

2024-02-08 09:14 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/plugin/index.ts
> +    figma.viewport.scrollAndZoomIntoView([figma.root]);
this line here doesn't work - when i click on the link in the list, its not going to point me to the icon.
Please modify this, such that when clicking on the link, it should bring the user to the icon.

2024-02-09 12:14 UTC, gnanammcp commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +      if (e.data.pluginMessage?.type === "tagAssets") {
As per your comments, I moved this code to the existing plugin structure.

2024-02-09 12:14 UTC, gnanammcp commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +              data.map((d, index) => (
I have changes param name as tag.

2024-02-15 15:35 UTC, gnanammcp commented on packages/@momentum-design/figma-plugin-assets-export/src/plugin/index.ts
> +    figma.viewport.scrollAndZoomIntoView([figma.root]);
I have done this implementation.

2024-02-16 09:59 UTC, cscheffauer approved these changes

2024-02-16 10:37 UTC, merged