test: jest-unit-test-transformer-files
momentum-design/momentum-design pull request #509
Opened 2024-02-06 04:20 UTC by kaviarasanopensource300

# Description

***required*** - *Description of the changes made in this Pull Request*
JEST unit test cases have been written for transformer files
1. manifest-transformer
2. svg-transformer
3.  swift-transformer
4. svg-glyphs-transformer

and few modification have ben made to existing unit test files
and added export to the SVGOptimized interface  inside the types file
## Links

***required*** - *Links to resources related to this Pull Request*

2024-02-06 08:31 UTC, cscheffauer requested changes

2024-02-06 08:31 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +  });
test is missing coverage for the method `transformFilesSync`

2024-02-06 08:31 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +});
test is missing coverage for the methods `transformFilesAsync` & `generateSVGFont`

2024-02-06 08:31 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +      await transformer.transformFilesSync();
this is a sync function - await is not necessary!

2024-02-06 08:31 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +      const optimizeSpy = jest.spyOn(transformer, 'optimize');
I would recommend to spy on `optimize` function from svgo, mock its return value to be `{ data: 'test' }` - that will allow you in line 37 to not do expect.anything(), but do a proper test, like `data: 'test'`. That will verify that the return of svgo's optimize does actually have an affect on the output

2024-02-06 08:31 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +      transformer.inputFiles = [{ srcPath: 'font', distPath: 'font', data: mockSVGFontBuffer }];
i would recommend adding 2 files here

2024-02-06 08:31 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +  });
test is missing `coverage` for the method transformFilesAsync

2024-02-08 04:34 UTC, merajcal commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +  });
did we already enable jest code coverage threshold?

2024-02-08 09:15 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +  });
not yet, will add to todos, good catch!

2024-02-12 08:11 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +});
transformFilesAsync  is in public  mode and call is successful. But for the generateSVGFont, since it is private, we cannot test this function.

2024-02-12 08:11 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +      await transformer.transformFilesSync();
I have updated it in the code

2024-02-12 08:15 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +  });
transformFilesSync. when this function is in test file.  Following error is coming.
![manifest transformer unit test ts](https://github.com/momentum-design/momentum-design/assets/157698966/71b2b7ad-a521-40de-ab8f-8a294fd2ac27)

2024-02-16 04:54 UTC, gauravchauhan3030 commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +      transformer.inputFiles = [{ srcPath: 'font', distPath: 'font', data: 'mockSVGFontBuffer' }];
why passed mockSVGFontBuffer as string

2024-02-16 04:54 UTC, gauravchauhan3030 commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +          data: 'mockSVGFontBuffer',
same here mockSVGFontBuffer as string not as buffer.

2024-02-28 09:37 UTC, cscheffauer requested changes
initial review, just got till the svg-glyphs-transformer unit tests - there are too many issues to finish this PR in a proper manner.

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          data: expect.any(String),
I would recommend to not use `expect.any(String)` here, cause we want to verify that the actual code works. Therefore please pass in a `srcPath` in line 31 with `/` inside, and then verify this data attribute here properly.

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          distPath: path.join('/dist', 'MyFont'),
instead of 'MyFont' use `DIST_NAME` variable here, as its defined as a const on top of the test file

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +      transformFilesSyncSpy.mockRestore();
this line is not necessary

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +      expect(transformFilesSyncSpy).toHaveBeenCalled();
this line is redundant to the line above

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +          data: expect.any(String),
same comment as above, test the real value here, instead of expect.any

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +          distPath: path.join('/dist', 'MyFont'),
same comment as above, use const `DIST_NAME` instead of MyFont

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +      const getNextCodepointSpy = jest.spyOn(Utils, 'getNextCodepoint');
testing this here doesn't make sense - this test should be done in the utils folder as a separate test for the getNextCodepoint.
Move this test into the utils folder.

Same for function testing sample 2 below

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +    it('should return the correct data from the promise of transformFilesSync() function', () => {
transformFilesSync is not a Promise!

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +      expect(getNextCodepointmockedfn()).toBe(556);
this line here doesn't provide any value, since we can assume that jest works correctly and mocks the return value.
remove this line

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +      Utils.getNextCodepoint();
this line here is wrong - why firing the util?

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +      // expect(transformer.outputFiles).toBe([
commented code should not be committed

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +      transformFilesSyncSpy.mockRestore();
mockRestore is not necessary

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +          distPath: path.join('/dist', 'MyFont'),
same as above, use `DIST_NAME`

2024-02-28 09:37 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +  // describe('transformFilesSync', () => {
commented code should not be committed

2024-02-28 10:41 UTC, cscheffauer commented
closing in favor of creating individual PRs per file

2024-02-28 10:41 UTC, closed without merging