test: jest-unit-test-cases-transformers manifest transformer unit test file
momentum-design/momentum-design pull request #537
Opened 2024-02-28 10:30 UTC by kaviarasanopensource300

…t file

# Description

***required*** - *Description of the changes made in this Pull Request*

## Links

***required*** - *Links to resources related to this Pull Request*

2024-02-28 10:40 UTC, cscheffauer requested changes

2024-02-28 10:40 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          data: expect.any(String),
I would recommend to not use expect.any(String) here, cause we want to verify that the actual code works. Therefore please pass in a srcPath in line 31 with / inside, and then verify this data attribute here properly.

2024-02-28 10:40 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          distPath: path.join('/dist', 'MyFont'),
instead of 'MyFont' use DIST_NAME variable here, as its defined as a const on top of the test file

2024-02-28 10:40 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +      transformFilesSyncSpy.mockRestore();
this line is not necessary

2024-02-28 10:40 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +      expect(Array.isArray(transformer.outputFiles)).toBe(true);
this is not necessary, since you are checking for it to be an array in the line below

2024-02-28 10:43 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +      transformFilesSyncSpy.mockRestore();
I have removed this line

2024-02-28 10:45 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          distPath: path.join('/dist', 'MyFont'),
I have added DIST_NAME variable in place of static code

2024-02-28 11:06 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          data: expect.any(String),
![image](https://github.com/momentum-design/momentum-design/assets/157698966/ae69f182-3673-45c6-8fa2-ccab220b7064)


data: '{\n  "font": "./font"\n}',  works

2024-02-28 11:10 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          data: expect.any(String),
expected data and received data are matching. Test is passed here also.

2024-02-28 11:38 UTC, cscheffauer requested changes

2024-02-28 11:38 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          data: '{\n  "font": "./font"\n}',
i would recommend to do it like this:
`data: JSON.stringify({font: "./font"})`

also this doesn't check the functionality of the code. Please pass in a proper srcPath (as i mentioned in the comment already). something like `/font/file.extension` would work

2024-02-29 02:57 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          data: '{\n  "font": "./font"\n}',
data: JSON.stringify(JSON.parse('{"font":"./font"}'), null, 2),  is added

2024-02-29 05:10 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          data: '{\n  "font": "./font"\n}',
![image](https://github.com/momentum-design/momentum-design/assets/157698966/d764ff26-f4f8-42b9-aa51-1863c84eaa6d)


srcPath: ''  is there in the manifest-transformer.ts  file.   In the unit test  file, we are checking the srcPath to be empty

2024-02-29 11:29 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +          data: '{\n  "font": "./font"\n}',
this comment wasn't addressed correctly, as mentioned pass in a proper srcPath

2024-03-01 09:30 UTC, cscheffauer requested changes

2024-03-01 09:30 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +      // mockSVGFontBuffer
comments should not be committed

2024-03-01 09:51 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/manifest-transformer.unit.test.ts
> +      // mockSVGFontBuffer
I have removed comments. Please do the needful.

2024-03-01 09:56 UTC, cscheffauer approved these changes

2024-03-01 09:56 UTC, merged