feat: ios tokens kebab case to camel case
momentum-design/momentum-design pull request #539
Opened 2024-02-29 04:52 UTC by gauravchauhan3030

ios tokens kebab case to camel case

2024-02-29 08:38 UTC, cscheffauer requested changes
the pipeline is broken, please check

2024-02-29 08:38 UTC, cscheffauer commented on packages/@momentum-design/tokens/config/tokens/core.json
> +  "transforms": ["ATTRIBUTE_CTI", "NAME_CTI_KABAB", "NAME_CTI_CAMEL", "MD_ELEVATION"]
all of the transforms here shouldn't be necessary anymore, since the transforms are inferred from the formats now.

2024-03-07 08:22 UTC, gauravchauhan3030 commented on packages/@momentum-design/tokens/config/tokens/core.json
> +  "transforms": ["ATTRIBUTE_CTI", "NAME_CTI_KABAB", "NAME_CTI_CAMEL", "MD_ELEVATION"]
removed

2024-03-12 04:53 UTC, gnanammcp approved these changes

2024-03-19 11:00 UTC, cscheffauer approved these changes

2024-03-19 11:04 UTC, merged