test: jest-unit-test-cases-transformers svg transformer unit test
momentum-design/momentum-design pull request #543
Opened 2024-03-05 05:20 UTC by kaviarasanopensource300

# Description
test: jest-unit-test-cases-transformers svg transformer unit test
Added the unit test file for the svg-transformer.ts
Added the export to the interface OptimizedSVGFormat 

***required*** - *Description of the changes made in this Pull Request*

## Links

***required*** - *Links to resources related to this Pull Request*

2024-03-07 07:11 UTC, bhanusengar reviewed
Reviewed 
Few changes already suggested.

2024-03-07 09:28 UTC, gauravchauhan3030 requested changes

2024-03-08 04:57 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +      expect(mockedoptimizeSVGOData()).toBe('Mocked data');
I have removed this test condition.

2024-03-08 04:57 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +  describe('1st - testing optimize function', () => {
Yes. I have wrapped all it functions in a single describe block.

2024-03-19 09:32 UTC, closed without merging