feat: added loading spinner for g tag detector implementation
momentum-design/momentum-design pull request #544
Opened 2024-03-05 06:25 UTC by gnanammcp

# Description

Figma Plugin / Add loading spinner to <g> tag detector

## Links

***required*** - *Links to resources related to this Pull Request*

2024-03-07 06:50 UTC, bhanusengar approved these changes

2024-03-07 09:38 UTC, gauravchauhan3030 approved these changes

2024-03-07 09:46 UTC, cscheffauer requested changes

2024-03-07 09:46 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +  const [loader, setLoader] = useState<boolean>(true);
naming this `isLoading` would be more meaningful. The name `loader` could be missunderstood

2024-03-07 09:46 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +  }, [gTagAssetUpdate]);
the dependency array here is missing the "show" attribute

2024-03-07 09:46 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +    setTimeout(() => {
why is this timeout necessary?

2024-03-07 09:46 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +    setLoader(true);
isLoading is set to true when closing the modal? that doesn't make sense

2024-03-07 09:46 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/hooks/useStateHandlers.ts
> +  const [gTagAssetUpdate, setGTagAssetUpdate] = useState<boolean>(false);
what does this `gTagAssetUpdate` do?

2024-03-11 09:16 UTC, gnanammcp commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +  const [loader, setLoader] = useState<boolean>(true);
changed as isLoading.

2024-03-11 09:16 UTC, gnanammcp commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +  }, [gTagAssetUpdate]);
removed this code

2024-03-11 09:17 UTC, gnanammcp commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/hooks/useStateHandlers.ts
> +  const [gTagAssetUpdate, setGTagAssetUpdate] = useState<boolean>(false);
removed this code and changed

2024-03-11 09:18 UTC, gnanammcp commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +    setTimeout(() => {
we are calling parent.postMessage and on message is async and await function so here I am using timeout.

2024-03-12 09:02 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +    setTimeout(() => {
async functions should be awaited! no timeout necessary.

2024-03-12 09:20 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/sections/tools/Tools.tsx
> +    setTimeout(() => {
checked - this is necessary. please add a comment to describe the reasoning

2024-03-12 09:20 UTC, cscheffauer approved these changes

2024-03-12 09:47 UTC, cscheffauer approved these changes

2024-03-12 09:48 UTC, merged