test:jest-unit-test-cases-transformer swift transformer file
momentum-design/momentum-design pull request #547
Opened 2024-03-07 02:13 UTC by kaviarasanopensource300

# Description
test:jest-unit-test-cases-transformer swift transformer file
added the unit test for the swift transformer file
***required*** - *Description of the changes made in this Pull Request*

## Links

***required*** - *Links to resources related to this Pull Request*

2024-03-07 05:28 UTC, bhanusengar requested changes

2024-03-07 05:59 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +  const FORMAT: Formats = { config: { fileName: 'MyFont', hbsPath: 'hpath' }, type: 'SWIFT' } as unknown as SwiftFormat;
Yes. I have removed unknown

2024-03-07 05:59 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +        data: '{"0": {"name": "accessibility-bold","srcPath" : "testPath","codepoint" : "61697","codepointHexa" : "f101","unicode" : "testUnicode"}}',
yes. I have stored in a variable.

2024-03-07 06:26 UTC, bhanusengar approved these changes
approved

2024-03-07 09:27 UTC, gauravchauhan3030 requested changes

2024-03-07 10:10 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +  const FORMAT: Formats = { config: { fileName: 'MyFont', hbsPath: 'hpath' }, type: 'SWIFT' } as unknown as SwiftFormat;
Yes. I have removed.

2024-03-08 03:43 UTC, kaviarasanopensource300 commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +  const FORMAT: Formats = { config: { fileName: 'MyFont', hbsPath: 'hpath' }, type: 'SWIFT' } as unknown as SwiftFormat;
I have removed unknown.

2024-03-19 09:32 UTC, closed without merging