feat(documentation): add api-extractore, api-doc, es-lint fixes #27
momentum-design/momentum-design pull request #55
Opened 2022-11-02 17:15 UTC by torgeadelin

# Description

Added following packages:
- api-extractor: generate API metadata
- api-documenter: using API metadata, generate markdown API for the package
- [eslint-plugin-tsdoc](https://www.npmjs.com/package/eslint-plugin-tsdoc) - eslint rule for tsdocs

Also added scripts to generate metadata and the markdown.

## Links

#27

2022-11-02 17:27 UTC, chrisadubois requested changes

2022-11-02 17:27 UTC, chrisadubois commented on package.json
> +    "eslint-plugin-tsdoc": "^0.2.17",
a docs script should be added to the main package json

docs script should be added to each package that exists

docs script should be added to the template plop generator

api extractor config should be added to the template plop generator as well as the eslint config

docs script should be added to the list of affected scripts that run so that this will trigger during CI/CD to generate docs

2022-11-02 17:29 UTC, chrisadubois reviewed
why is it generating so many files? shouldn't these be consolidated ???

2022-11-02 17:29 UTC, chrisadubois commented on .eslintrc.cjs
> +    'eslint-plugin-tsdoc',
👍

2022-11-02 17:29 UTC, chrisadubois commented on .eslintrc.cjs
> +    'tsdoc/syntax': 'warn',
👍

2022-11-03 10:13 UTC, torgeadelin commented on package.json
> +    "eslint-plugin-tsdoc": "^0.2.17",
re `docs script should be added to each package that exists` -- tokens package is just a db, it doesn't have any code, only JSON files.

2022-11-03 10:15 UTC, torgeadelin commented on package.json
> +    "eslint-plugin-tsdoc": "^0.2.17",
re `docs script should be added to the template plop generator` -- added

2022-11-03 11:03 UTC, torgeadelin commented on package.json
> +    "eslint-plugin-tsdoc": "^0.2.17",
re `a docs script should be added to the main package json` -- added

2022-11-03 11:10 UTC, torgeadelin commented on package.json
> +    "eslint-plugin-tsdoc": "^0.2.17",
re `api extractor config should be added to the template plop generator as well as the eslint config` -- added api-extractor config to plop templates (also fixed some small bugs).
re `eslint config to plop` -- the es lint rule I've added is global for the monorepo not individual to each package.

2022-11-03 14:10 UTC, torgeadelin commented on package.json
> +    "eslint-plugin-tsdoc": "^0.2.17",
@chrisadubois ready for re-review

2022-11-03 15:04 UTC, chrisadubois approved these changes

2022-11-03 16:45 UTC, closed without merging