fix: illustrations icon fix for docs module
momentum-design/momentum-design pull request #551
Opened 2024-03-19 04:24 UTC by gauravchauhan3030

illustrations icon fix for docs module

2024-03-19 09:51 UTC, bhanusengar commented on packages/@momentum-design/docs/src/components/IllustrationTable/IllustrationTable.tsx
> +      .filter(([key]) => (query ? key.includes(query) && key.includes(IllustrationSize[size as unknown as keyof typeof IllustrationSize]) : key.includes(IllustrationSize[size as unknown as keyof type
In line 84 i think you can try instead of rewriting  `keyof typeof IllustrationSize` twice
`type IllustrationSIZE = keyof typeof IllustrationSize;` on top  and use type variable

2024-03-26 10:12 UTC, bhanusengar approved these changes

2024-04-02 08:48 UTC, cscheffauer requested changes

2024-04-02 08:48 UTC, cscheffauer commented on packages/@momentum-design/docs/src/components/IllustrationTable/constants.ts
> +export type illustrationSizeType = keyof typeof IllustrationSize;
Types and constants shouldn't be mixed in a module.
Either split the files into 2, or you can define the type in the IllustrationTable at the top directly.
Also additionally: Types should always be Capitalized, like `IllustrationSizeType`

2024-04-02 16:30 UTC, cscheffauer approved these changes

2024-04-03 14:52 UTC, merged