test: unit test case for swift transformer
momentum-design/momentum-design pull request #553
Opened 2024-03-20 05:38 UTC by bhanusengar

# Description

Unit test case for swift transformer.

2024-03-22 04:40 UTC, gnanammcp approved these changes

2024-03-26 09:12 UTC, cscheffauer requested changes

2024-03-26 09:12 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +          distPath: path.join('/dist', 'MyFont'),
u can use `FORMAT.config.fileName` here instead of `MyFont`.
Also the `/dist` can be extracted to a constant and being used in line 18 and 30 and here

2024-03-26 09:12 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +const inputFilesData = { 0: {
not quite sure why `{ 0: ...` is necessary here - can u try to create the inputFilesData without it, just being a non-nested object?

2024-03-26 14:15 UTC, bhanusengar commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +          distPath: path.join('/dist', 'MyFont'),
Changes added.

2024-03-26 14:15 UTC, bhanusengar commented on packages/@momentum-design/builder/src/assets/builder/transformer/swift-transformer.unit.test.ts
> +const inputFilesData = { 0: {
Changes addressed.

2024-04-02 08:45 UTC, cscheffauer approved these changes

2024-04-02 08:49 UTC, merged