feat: test cases for svg glyph transformer file
momentum-design/momentum-design pull request #555
Opened 2024-03-22 09:25 UTC by gauravchauhan3030

test cases for svg glyph transformer file

2024-03-26 14:38 UTC, gnanammcp approved these changes

2024-04-02 08:14 UTC, cscheffauer requested changes

2024-04-02 08:14 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +  describe('getNextCodepoint', () => {
Can u split this test out to a separate test file, along with the utils? like the getNextCodepoint is part of a different file, so we would want to have a separate test file for that

2024-04-02 08:14 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-glyphs-transformer.unit.test.ts
> +    it('transform the passed in files by optimizing each of them', () => {
the `generateGlyphsData` does have more functionality in it, we would want to test (in specific line 25, where we filter out input files if they include numbers). We would want to have a separate test case which tests that inputFiles with a srcPath with a number in it will be filtered out

2024-04-04 07:51 UTC, cscheffauer approved these changes

2024-04-04 08:20 UTC, merged