fix: git release history
momentum-design/momentum-design pull request #560
Opened 2024-03-26 08:39 UTC by bhanusengar

# Description

- Only show last/latest commit 
- Format release description

2024-03-26 14:38 UTC, gnanammcp approved these changes

2024-04-02 08:01 UTC, cscheffauer requested changes
some small changes, otherwise looking good!

2024-04-02 08:01 UTC, cscheffauer commented on packages/@momentum-design/automation/src/utils/git/git.ts
> +  public static async getPullRequestDetails(commitSHA:string): Promise<any> {
can we somehow type this more precise? like instead of `Promise<any>` can we do like `Promise<Array...>` (i don't know what the exact response of this is)

2024-04-02 14:47 UTC, gauravchauhan3030 commented on packages/@momentum-design/automation/src/commands/create-release/create-release.ts
> +      const notes = `### ${commitLog[0].subject}\r\n${pullRequestDesciption[0].body}`
It will be better if you abstract these strings into constants for readability perspective.

2024-04-08 09:19 UTC, bhanusengar commented on packages/@momentum-design/automation/src/utils/git/constants.ts
> +const REPO_URL = 'https://api.github.com/repos/momentum-design/momentum-design/commits';
Changes addressed.

2024-04-08 09:19 UTC, bhanusengar commented on packages/@momentum-design/automation/src/commands/create-release/create-release.ts
> +      const pullRequestDesciption = await Git.getPullRequestDetails(commitLog[0].commit);
Changes addressed.

2024-04-08 09:23 UTC, cscheffauer approved these changes

2024-04-08 09:23 UTC, merged