svg-transformer file test cases
momentum-design/momentum-design pull request #570
Opened 2024-04-04 10:39 UTC by gauravchauhan3030

svg transformer file test cases

2024-04-05 04:01 UTC, gnanammcp approved these changes

2024-04-05 08:11 UTC, cscheffauer requested changes

2024-04-05 08:11 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +      const svgoOptimizeSpy = jest.spyOn(transformer, 'optimize');
the naming `svgoOptimizeSpy` here is not correct - it is spying on the optimize function of the transformer, not the svgo package

2024-04-05 08:11 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +      expect(result).toEqual({ distPath: DIST_PATH, srcPath: SRC_PATH, data: expect.any(String) });
can this be more accurate than `expect.any(String)` ?

2024-04-05 08:11 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/svg-transformer.unit.test.ts
> +    it('checks optimize(svgoOptimize) function of svgo library called', () => {
this can be merged with the test case above

2024-04-10 09:18 UTC, cscheffauer approved these changes

2024-04-10 09:26 UTC, merged