fix: Brand Visual export png and svg
momentum-design/momentum-design pull request #662
Opened 2024-07-04 07:33 UTC by arjunkesava

# Description

- This PR is a fix on the existing PR: https://github.com/momentum-design/momentum-design/pull/614
- 13937cd33d8d091d7179561e5565f21f641d0757 - this commit fixes the file extension so that png will also be added.

## Links

Here is the example PR which is the result of this PR: https://github.com/momentum-design/momentum-design/pull/661
We can now upload both png and svg files into the brand visuals export library.

2024-07-04 08:27 UTC, cscheffauer requested changes
looking good - some issues / gaps to work on before merging

2024-07-04 08:27 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/plugin/models/component.ts
> +  isNodeContainingImage(node: ComponentNode) {
issue: any source code change should come with a unit test / test change.

2024-07-04 08:27 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/shared/types.ts
> +  readonly format: 'JPG' | 'PNG';
issue: my recommendation would be to only set format 'PNG' here, since we do not need to support JPG for now, this PR was only tested with PNG - because of that we should not introduce a type which gives future developers the feeling that we also support JPG (which we don't)

2024-07-04 08:27 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/ui/models/github.ts
> +        if (cur.path.match(/\.(jpg|jpeg|png|gif)$/i)) {
issue: we only tested png, thats why my suggestion would be to put png only here for now to not cause confusion.

2024-07-04 09:58 UTC, arjunkesava commented on packages/@momentum-design/figma-plugin-assets-export/src/plugin/models/component.ts
> +  isNodeContainingImage(node: ComponentNode) {
Yes, I will add unit test in this ticket: https://jira-eng-gpk2.cisco.com/jira/browse/SPARK-483011

2024-07-04 17:05 UTC, cscheffauer submitted a review, later dismissed

2024-07-04 17:05 UTC, cscheffauer commented on packages/@momentum-design/figma-plugin-assets-export/src/plugin/models/component.unit.test.ts
> +      componentNodeMock.exportAsync.mockImplementation(() => Promise.resolve(''));
mocking the implementation to resolve with a empty string doesn't match the expected return value of the exportAsync. please mock this properly.

2024-07-08 12:20 UTC, cscheffauer approved these changes

2024-07-08 12:20 UTC, merged