chore: add CSS format support to builder
momentum-design/momentum-design pull request #666
Opened 2024-07-09 11:50 UTC by rajrdas

# Description

- *Added support to builder to generate CSS file for the icons*

## Links

***required*** - *Links to resources related to this Pull Request*

2024-07-09 12:35 UTC, cscheffauer requested changes

2024-07-09 12:35 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/css-transformer.ts
> +import { promisify } from 'util';
we aren't using promisify anywhere else and there shouldn't be a reason to do so. Just use the normal async/await or Promise.then syntax for fs.readfile.

2024-07-09 12:35 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/transformer/css-transformer.ts
> +        woffUrl: await this.getFileNameWithHash(this.format.config.woffPath),
is there a reason why we hash the filename? i think there is no need for it imho.

2024-07-09 12:35 UTC, cscheffauer commented on packages/@momentum-design/icons/config/templates/momentum.css.hbs
> +@font-face {
has this been tested locally? i tried your PR locally and ran yarn icons build and it did create a empty css file with no content. can u check again please?

2024-07-09 12:35 UTC, cscheffauer commented on packages/@momentum-design/builder/src/assets/builder/types.ts
>    // TODO: add CSS config type:
this type can be fixed now

2024-07-15 10:17 UTC, rajrdas commented on packages/@momentum-design/icons/config/templates/momentum.css.hbs
> +@font-face {
This has worked for me.

2024-07-16 16:02 UTC, cscheffauer approved these changes

2024-07-16 16:03 UTC, merged