feat: upgrade all the dependencies in the package.json of icons
momentum-design/momentum-design pull request #707
Opened 2024-07-30 07:00 UTC by 2020Deeya

# Description

Upgrade all the dependencies in the package.json of icon

2024-07-30 07:09 UTC, cscheffauer requested changes

2024-07-30 07:09 UTC, cscheffauer commented on packages/@momentum-design/icons/package.json
> +    "rimraf": "^6.0.1"
This change also will cause yarn.lock file changes, which will be needed as part of the commit

2024-07-30 12:40 UTC, 2020Deeya commented on packages/@momentum-design/icons/package.json
> +    "rimraf": "^6.0.1"
Resolved

2024-08-08 16:29 UTC, 2020Deeya commented
Dependencies are already merged into main using syncpack. Hence, closing the PR.

2024-08-08 16:29 UTC, closed without merging