feat: upgrade all the dependencies in the package.json of illustrations
momentum-design/momentum-design pull request #708
Opened 2024-07-30 07:06 UTC by 2020Deeya

# Description

Upgrade all the dependencies in the package.json of illustrations

2024-07-30 07:08 UTC, cscheffauer requested changes

2024-07-30 07:08 UTC, cscheffauer commented on packages/@momentum-design/illustrations/package.json
> +    "rimraf": "^6.0.1"
For this change there should also be a yarn.lock file change, which needs to be committed as well.

2024-07-30 12:44 UTC, 2020Deeya commented on packages/@momentum-design/illustrations/package.json
> +    "rimraf": "^6.0.1"
Resolved

2024-08-08 12:12 UTC, 2020Deeya commented
Dependencies are already merged into main using syncpack. Hence, closing the PR.

2024-08-08 12:12 UTC, closed without merging