feat(specs): run unit tests for automation commands
momentum-design/momentum-design pull request #732
Opened 2024-08-06 17:43 UTC by arjunkesava

# Description

- Write unit tests for the commands `get-packages` and `increment-packages`.
- Implement `dryRun` for increment packages command as we don't need to update package files for a unit spec.
- Set up the package.json scripts to run tests in the automation package.

<img width="1728" alt="Screenshot 2024-08-06 at 10 54 17 PM" src="https://github.com/user-attachments/assets/cf48fa1c-b3ee-4285-9ccf-1b75973576a1">

2024-08-08 17:18 UTC, cscheffauer requested changes

2024-08-08 17:18 UTC, cscheffauer commented on packages/@momentum-design/automation/package.json
> +    "test:postbuild": "yarn build && yarn test:unit:postbuild",
postbuild in the pipeline runs "after" the build automatically, there is no need to build here

2024-08-08 17:18 UTC, cscheffauer commented on packages/@momentum-design/automation/src/commands/increment-packages/constants.ts
> +    describe: 'dry run mode, does not write changes to disk',
i would add `or sends requests to NPM, other services`

2024-08-08 17:18 UTC, cscheffauer commented on packages/@momentum-design/automation/src/commands/main/main.test.ts
> +    it('increment version count for all packages', async () => {
what would be great here is to also have tests for "create-release" command

2024-08-08 17:18 UTC, cscheffauer commented on packages/@momentum-design/automation/src/commands/main/main.test.ts
> +import { Execute } from '../../utils';
having all those tests in one test file is not scalable, i think it would be better to create for each command a test file, like in get-packages, increment-packages folder etc.
You can name the test file like `XXX.postbuild-test.ts` and in the jest.config just target those test files (makes it more scalable)

2024-09-04 05:55 UTC, arjunkesava commented
Closing this PR, as I've opened a new one at #803

2024-09-04 05:55 UTC, closed without merging