feat: add unit tests for High contrast tokens
momentum-design/momentum-design pull request #798
Opened 2024-08-30 13:55 UTC by 2020Deeya

# Description

Added unit tests for High contrast tokens.

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-54

2024-08-30 14:08 UTC, 2020Deeya commented
![image](https://github.com/user-attachments/assets/d9346a4d-a1bf-4c75-8038-3faef3af0a00)

The PR will fail when executing the test cases because the description for the WindowTextColor token does not follow the expected format. For instance, 
Current Description: "Text main color"
Expected Description: Should start with the format SystemColorXXX, where XXX refers to the token name. It should be SystemColorWindowTextColor in this case.

2024-08-30 16:08 UTC, arjunkesava requested changes

2024-08-30 16:08 UTC, arjunkesava commented on packages/assets/tokens/src/core/value.test.ts
> +const expectedColors = require('./mappingTable');
I sense a problem with this approach.
- As the `value.json` file is generated by the `token.studio` figma plugin, if there is any update in the Tokens Figma file, then these specs get failed.
- Instead of validating the system color postfix, we can make a new regexp and expect the entire data in value.json file to match the regexp everytime.

2024-09-02 09:01 UTC, cscheffauer commented on packages/assets/tokens/src/core/value.test.ts
> +const expectedColors = require('./mappingTable');
the point of this unit test is to make sure that the changes made by token studio are actually what we expect. Typos or unwanted changes for these SystemColors should be avoided, since Windows requires them to be accurate.
Thats why we write this test originally.

Any other changes in the tokens themselves should not be checked.

To your point 2, @arjunkesava : we only want the HighContrast Core Tokens to be validated.

2024-09-02 09:52 UTC, arjunkesava commented on packages/assets/tokens/src/core/value.test.ts
> +const expectedColors = require('./mappingTable');
Ohk, if the requirement is only to validate HighContrast Core Tokens, then we are good.

2024-09-02 09:52 UTC, arjunkesava submitted a review, later dismissed

2024-09-02 20:26 UTC, cscheffauer requested changes

2024-09-02 20:26 UTC, cscheffauer commented on packages/assets/tokens/src/core/value.test.ts
> +  test('Black high contrast tokens should match expected values and descriptions', () => {
nitpick: in other unit tests we have been using `it` to follow more the english wording, i.e. `it("should do ..."`.
maybe worth creating a ESLint rule for all packages to check this.

2024-09-02 20:26 UTC, cscheffauer commented on packages/assets/tokens/src/core/value.test.ts
> +      expect(blackColors[key].description).toBe(expectedBlackColors[key].description);
this assertion is more specific than the assertion in line 20. We do not need to check that the rest of the description matches our expectation, but only the start with the SystemColor is important. This line can be deleted

2024-09-02 20:26 UTC, cscheffauer commented on packages/assets/tokens/src/core/value.test.ts
> +      const tokenName = key;
no need to create this constant, key can be used directly

2024-09-02 20:26 UTC, cscheffauer commented on packages/assets/tokens/src/core/value.test.ts
> +      expect(whiteColors[key].description).toBe(expectedWhiteColors[key].description);
same comment as above

2024-09-02 20:26 UTC, cscheffauer commented on packages/assets/tokens/src/core/value.test.ts
> +      const tokenName = key;
same comment as above

2024-09-03 08:47 UTC, 2020Deeya commented on packages/assets/tokens/src/core/value.test.ts
> +  test('Black high contrast tokens should match expected values and descriptions', () => {
Resolved. 
For creating a ESLint rule for all packages to check this, let's work on separate PR.

2024-09-03 08:48 UTC, 2020Deeya commented on packages/assets/tokens/src/core/value.test.ts
> +      expect(blackColors[key].description).toBe(expectedBlackColors[key].description);
Agreed. Checking Prefix is enough.

2024-09-06 09:34 UTC, cscheffauer approved these changes

2024-09-06 09:34 UTC, merged