feat: create utils package under assets
momentum-design/momentum-design pull request #811
Opened 2024-09-06 11:37 UTC by 2020Deeya

# Description

- Create a new package with plop package generator and name the package @momentum-design/utils.
- The location of this package should be inside packages/assets

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-253

2024-09-06 14:50 UTC, supminn approved these changes
LGTM

2024-09-09 12:25 UTC, cscheffauer requested changes

2024-09-09 12:25 UTC, cscheffauer commented on packages/assets/utils/package.json
> +    "publish:npmjs": "echo \"script 'publish:npmjs' has not been implemented\"",
currently we will not publish this to NPM - i think we can change this line once we have the src code in. just a fyi

2024-09-09 12:26 UTC, cscheffauer approved these changes

2024-09-09 13:17 UTC, merged