feat: show playwright report as artifact in github actions
momentum-design/momentum-design pull request #823
Opened 2024-09-09 15:40 UTC by 2020Deeya

# Description

In order to save the artifact of Playwright, pull-request.yml file is adjusted to upload the playwright-report at the end of running the E2E tests.

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-267

2024-09-10 05:42 UTC, supminn submitted a review, later dismissed
LGTM

2024-09-10 07:56 UTC, cscheffauer requested changes

2024-09-10 07:56 UTC, cscheffauer commented on .github/workflows/pull-request.yml
> +      - name: Upload Playwright Report
i think it would be great to unzip the report first, then upload it, such that we can directly go to the html which is inside of the zip (with that we wouldn't need to download)

2024-09-10 07:56 UTC, cscheffauer commented on .github/workflows/pull-request.yml
> +        if: ${{ !cancelled() }}
at the moment this step runs in all packages, i.e. also runs if tokens Test - Postbuild runs.
We only want this step to run for components package - we could extend this if statement with a matrix.package comparison to make sure to only run this upload if the matrix.package is the components one.

2024-09-11 09:57 UTC, 2020Deeya commented on .github/workflows/pull-request.yml
> +      - name: Upload Playwright Report
As discussed, @estruyf/github-actions-reporter is added as a dependency in components, which reports test results from Playwright to GitHub summaries.

Reference PR for sanity testing: 
https://github.com/momentum-design/momentum-design/actions/runs/10808908015/job/29983068894

2024-09-11 12:28 UTC, cscheffauer requested changes

2024-09-11 12:28 UTC, cscheffauer commented on packages/components/package.json
> +    "@estruyf/github-actions-reporter": "^1.9.2",
this has been added as a dependency - it should be in "devDependencies". When adding dependencies make sure to add `--dev` when using yarn to install dependency in a package - or move it in the right dependency group.

2024-09-11 12:28 UTC, cscheffauer commented on packages/components/config/playwright/playwright.config.ts
> +    ['@estruyf/github-actions-reporter']
there is a bit of config i would suggest adding for this actions reporter here, which is:
```
import type { GitHubActionOptions } from '@estruyf/github-actions-reporter';

...
['@estruyf/github-actions-reporter', <GitHubActionOptions>{
      title: 'Playwright E2E Test results',
      useDetails: true,
      showTags: true,
      showError: true,
      includeResults: ['fail', 'flaky']
    }]
```

We can have a chat about how i ended up with this config and why.

2024-09-11 17:56 UTC, 2020Deeya commented on packages/components/package.json
> +    "@estruyf/github-actions-reporter": "^1.9.2",
Sure, have added it as a dev dependency.

2024-09-11 17:56 UTC, 2020Deeya commented on packages/components/config/playwright/playwright.config.ts
> +    ['@estruyf/github-actions-reporter']
Done, have incorporated these config options.

2024-09-13 12:38 UTC, cscheffauer submitted a review, later dismissed
small comment, other than that looking good

2024-09-13 12:38 UTC, cscheffauer commented on packages/components/config/playwright/playwright.config.ts
> +// GitHub Actions reporter options
nitpick: comment is a duplicate of the code, please remove

2024-09-15 16:05 UTC, 2020Deeya commented on packages/components/config/playwright/playwright.config.ts
> +// GitHub Actions reporter options
Done.

2024-09-16 07:01 UTC, cscheffauer approved these changes

2024-09-16 07:22 UTC, merged