chore: do not enforce yarn version in consuming projects
momentum-design/momentum-design pull request #824
Opened 2024-09-10 16:15 UTC by NotNestor

# Description

"packageManager": "yarn@3.2.4" ensures that the specified version of Yarn is used for the current project.
"engines": { "yarn": ">=3.0.0" } specifies the minimum version of Yarn required for consuming projects.

momentum-design should not dictate the the yarn version of consumers

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-268

2024-09-10 16:23 UTC, cscheffauer requested changes

2024-09-10 16:23 UTC, cscheffauer commented on packages/components/package.json
> +    "npm": ">=8.0.0"
as discussed, lets remove it just in the prepublish script, but keep it in the package.json.
We want to enforce this for contributors, locally developing.

We want to remove it when publishing

2024-09-10 16:27 UTC, NotNestor commented on packages/components/package.json
> +    "npm": ">=8.0.0"
no it should be removed in engines packageManager already tells what version should be used when building the project. yarn should be removed from engines

2024-09-12 09:36 UTC, cscheffauer approved these changes

2024-09-12 09:36 UTC, merged