fix(spec): add req packages to build for test setup
momentum-design/momentum-design pull request #834
Opened 2024-09-12 19:37 UTC by arjunkesava

# Description

- Problem: The PR pipeline fails randomly due to a weird error. Ex: [failure action](https://github.com/momentum-design/momentum-design/actions/runs/10683196872/job/29610843997)
 <img width="669" alt="image" src="https://github.com/user-attachments/assets/f7b4cf1d-b108-4bf8-a9d4-2003afce7d93">

- After research, we found that to run this below script, we need the necessary packages to be `build` before to run this.
- https://github.com/momentum-design/momentum-design/blob/0e45a7bf8f646476012297d8c22a0507ebfd6901/packages/components/package.json#L43
- As github workflows run parallelly, there is no guarantee that the build will execute just before this script gets started.
- This PR will fix this issue by adding a mandatory `build step` so that it will build all the needed packages to run before `playwright` runs the above step.
- Here is the successful output:
![Screenshot 2024-09-12 at 9 24 48 PM](https://github.com/user-attachments/assets/0b142105-9a7e-471e-a3ea-5bdde2b2b383)

##### Credits to `act` by https://github.com/nektos/act.
##### With the help of this, we were able to find the reason behind this error.

## Links

- JIRA Ticket

2024-09-13 05:35 UTC, arjunkesava commented on packages/components/config/playwright/playwright.config.ts
> +    command: 'yarn build:test-deps && yarn test:e2e:setup',
FYI: Instead of the script [build:test-deps](https://github.com/momentum-design/momentum-design/blob/8350b6066808af7b6ff9fe495ddac08c2051a112/packages/components/package.json#L26), we can `cd` to the project root directory and run `yarn build` and again come back over here.

2024-09-13 05:36 UTC, arjunkesava commented on packages/components/package.json
> +    "build:test-deps": "yarn workspace @momentum-design/telemetry build && yarn workspace @momentum-design/token-builder build && yarn workspace @momentum-design/tokens build && yarn workspace @momen
These are all the scripts which were needed to run "copy:tokens, copy:icons and copy:fonts scripts".

2024-09-26 14:09 UTC, cscheffauer requested changes

2024-09-26 14:09 UTC, cscheffauer commented on packages/components/config/playwright/playwright.config.ts
> +    command: 'yarn build:test-deps && yarn test:e2e:setup',
this command runs locally as well - we do not want that.
Instead i would recommend to edit the pipeline (pull-request.yml) itself

2024-09-26 14:09 UTC, cscheffauer commented on packages/components/package.json
> +    "build:test-deps": "yarn workspace @momentum-design/telemetry build && yarn workspace @momentum-design/token-builder build && yarn workspace @momentum-design/tokens build && yarn workspace @momen
this is a dependency in the component package on other dependencies - yarn workspaces can figure that dependency tree out - i would vote for the pull-request.yml file approach though, which is not having a script like u have but just run yarn build as part of the test:post-build directly again.

2024-10-02 07:31 UTC, cscheffauer approved these changes

2024-10-02 07:31 UTC, merged