fix: host storybook in astro docs
momentum-design/momentum-design pull request #848
Opened 2024-09-19 08:59 UTC by 2020Deeya

# Description

In order to expose the storybook within our components package to consumers, 

- Include storybook code into the existing astro docs

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-283

2024-09-25 08:35 UTC, cscheffauer requested changes

2024-09-25 08:35 UTC, cscheffauer commented on packages/assets/fonts/src/css/fonts.css
> +    src: url("../fonts/Inter.var.woff2") format("woff2");
the path here is broken in the dist of the fonts package - we should set it such that it works as it is in the fonts package and not change it for other packages.
![image](https://github.com/user-attachments/assets/59acdf0b-fdb5-4512-8767-aea57a651a15)

2024-09-25 08:35 UTC, cscheffauer commented on packages/components/package.json
> +    "./storybook-static": "./dist/storybook-static"
issue: this export should not be here - we should not include the storybook-static in the NPM package.

2024-09-25 08:35 UTC, cscheffauer commented on packages/components/package.json
> +    "build": "yarn build:module && yarn build:browser && yarn build-storybook",
issue: we should not include the build-storybook in the normal build, since the normal build is about creating the dist folder for the npm package release. Just keep build-storybook separate and we can modify the github actions for documentation to run this.

2024-09-25 08:35 UTC, cscheffauer commented on packages/components/package.json
> +    "build-storybook": "storybook build -c config/storybook -o dist/storybook-static",
suggestion: for the sake of consistency we could do `build:storybook` here for the script name

2024-09-25 08:35 UTC, cscheffauer commented on packages/components/config/storybook/provider/iconProvider.js
> +        url="./icons/svg"
issue: just tried the storybook in the docs locally and it seems like the icon component is broken.
Please check

did yarn docs build / yarn docs preview

2024-09-25 09:24 UTC, 2020Deeya commented on packages/components/package.json
> +    "build-storybook": "storybook build -c config/storybook -o dist/storybook-static",
Done

2024-09-25 09:26 UTC, 2020Deeya commented on packages/components/config/storybook/provider/iconProvider.js
> +        url="./icons/svg"
I did yarn docs build and then, yarn docs preview. It has worked for me. We can verify it offline.

2024-09-25 09:33 UTC, 2020Deeya commented on packages/components/package.json
> +    "./storybook-static": "./dist/storybook-static"
We used this export approach to easily access the storybook-static folder through dynamic module resolution with import.meta.resolve. Since we don't want to include the storybook-static folder in the NPM package, I have now removed the 18th line that exports storybook-static.

2024-09-26 05:42 UTC, 2020Deeya commented on packages/assets/fonts/src/css/fonts.css
> +    src: url("../fonts/Inter.var.woff2") format("woff2");
Resolved the relative paths of fonts.

2024-09-27 08:16 UTC, cscheffauer requested changes
some small comments, otherwise looking good

2024-09-27 08:16 UTC, cscheffauer commented on packages/components/scripts/copyFonts.js
> +const fontsFolder = path.join(root, '..', 'assets', 'fonts', 'dist');
suggestion: in this case i would still vote for having the require.resolve

2024-09-27 08:16 UTC, cscheffauer commented on packages/documentation/astro.config.mjs
> +const getStorybookFolder = () => path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'components');
suggestion: this does not need to be a function

2024-09-27 09:42 UTC, 2020Deeya commented on packages/components/scripts/copyFonts.js
> +const fontsFolder = path.join(root, '..', 'assets', 'fonts', 'dist');
Done.

2024-09-27 09:42 UTC, 2020Deeya commented on packages/documentation/astro.config.mjs
> +const getStorybookFolder = () => path.join(path.dirname(fileURLToPath(import.meta.url)), '..', 'components');
Agreed.

2024-09-27 11:22 UTC, cscheffauer approved these changes

2024-09-27 11:48 UTC, merged