Icon provider updates
momentum-design/momentum-design pull request #868
Opened 2024-10-03 22:50 UTC by NotNestor

# Description

* Update "scale" to "size" across project
* Add size to icon provider
* Add allow list of length units
* Update yarn lock file
* Fix various warnings

## Links

N/A

2024-10-03 22:51 UTC, NotNestor commented on packages/components/config/playwright/setup/Components.page.ts
>      await expect(this.page).toHaveTitle(componentsDevPageTitle);
sonarlint prefers nullish coalescing over logical or

2024-10-03 22:52 UTC, NotNestor commented on packages/components/config/playwright/setup/utils/accessibility.ts
>     */
jsdocs expects - after param

2024-10-03 22:53 UTC, NotNestor commented on packages/components/src/components/avatar/avatar.component.ts
update scale to size across components

2024-10-04 08:37 UTC, cscheffauer requested changes

2024-10-04 08:37 UTC, cscheffauer commented on packages/components/src/components/badge/badge.component.ts
> +import '../icon';
i think we need to look at this closer - this line will register the icon component, but if someone just imports the Badge as a Class, we do not want the Icon component to be registered i think.
A possibly solution for this would be to move this import to the Badge index file.
This feels like we should come up with a convention for it.

2024-10-04 08:37 UTC, cscheffauer commented on packages/components/src/components/badge/badge.styles.ts
> +      --mdc-badge-icon-color: var(--mds-color-theme-common-text-primary-normal);
i will not review these lines here given we might change this later and its not really in scope of the iconprovider

2024-10-04 08:37 UTC, cscheffauer commented on packages/components/src/components/iconprovider/iconprovider.constants.ts
> +const LENGTH_UNIT_DEFAULT_SIZE:Record<string, number> = {
nitpick: i think this should be part of the DEFAULTS object for keeping all DEFAULTS together

2024-10-04 08:37 UTC, cscheffauer commented on packages/components/src/components/iconprovider/iconprovider.component.ts
> +   * This property can be set via the 'size' attribute.
this line is just repeating what is clear, given the TSDoc here is for the size attribute

2024-10-04 08:54 UTC, NotNestor commented on packages/components/src/components/badge/badge.styles.ts
> +      --mdc-badge-icon-color: var(--mds-color-theme-common-text-primary-normal);
no but when testing i want the icon colour to change with the background colour correctly for demoing purposes

2024-10-04 08:55 UTC, NotNestor commented on packages/components/src/components/iconprovider/iconprovider.component.ts
> +   * This property can be set via the 'size' attribute.
👍 will update

2024-10-04 09:42 UTC, supminn commented on packages/components/src/components/icon/icon.component.ts
> +    return this.size ?? this.sizeFromContext ?? DEFAULTS.SIZE;
question: do we need to add `DEFAULT.SIZE` here? Line52 would set the size to default value right? 
I'm not sure what value would this resolve to, since `this.size` would either have a value or take the `DEFAULT.SIZE`. This would never apply `this.sizeFromContext`. Is my understanding correct or does it work in a different way?

2024-10-04 10:30 UTC, NotNestor commented on packages/components/src/components/icon/icon.component.ts
> +    return this.size ?? this.sizeFromContext ?? DEFAULTS.SIZE;
Updated to remove default value from size property. Now if not set it will fall back

2024-10-04 11:54 UTC, cscheffauer approved these changes

2024-10-04 11:54 UTC, merged