fix: add consumption guide for components
momentum-design/momentum-design pull request #871
Opened 2024-10-07 07:30 UTC by 2020Deeya

# Description

Add a consumption guide specifically designed for the consumers of the Global Library, detailing how to effectively access and utilize it in their codebase.
As of now, it targets Web component and React. 

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-351

2024-10-07 13:30 UTC, cscheffauer requested changes

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/config/storybook/main.js
> +    '@storybook/addon-docs',
suggestion: addon-essentials does include already addon-docs, we don't need to add it i think.

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/package.json
> +    "@storybook/addon-docs": "^8.3.5",
suggestion: addon-essentials does include already addon-docs, we don't need to add it i think.

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/package.json
> +    "vite": "^5.4.8"
why was vite added as part of this?

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/CONSUMPTION.md
> +# Consumption Guide for Global web Library
we should remove this one here - thats what i mentioned whcih would be good to avoid:
We don't want 2 Consumption Guide docs, cause we always have to keep them in sync.
Lets just create one.

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +```bash
nitpick: use the right scripting language here, like `javascript` (instead of bash)
applies for all occurrences

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +# Consumption Guide for Global web Library
"Consumption Guide" should be enough, adding global web library here might cause confusion.

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +This consumption guide for the Global Library, `@momentum-design/components` provides detailed instructions on how to effectively access and utilize these components in your web applications, specifi
If u want to use `Global Library` here, i would recommend to do `Global Web Library` to stick to the term.

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +In order to execute, run the following command:
`In order to install` would be more suitable

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +* TypeScript > 4.7
This does not talk about what to do when using a higher version than Typescript 4.7.
Like this should describe whats the difference between using the typescript version (link to the Stackoverflow article i sent would be good as well)

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +* Your build config needs to be able to have file loaders for CSS and WOFF.
We require `WOFF2`

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +For detailed information about each component, refer to the [**Components Docs**](https://momentum-design.github.io/momentum-design/en/components/)
`refer to the individual ...` would make more sense

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +index.html
this could be part of the code snippet, like
```javascript
// index.html
...
```

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +<script src="@momentum-design/components/browser/index.js"></script>
you need some ... between the script and the avatar to indicate that the <mdc-avatar> is actually in the html / body etc.

2024-10-07 13:30 UTC, cscheffauer commented on packages/components/src/ConsumptionGuide.mdx
> +import { Avatar } '@momentum-design/components/react';
issue: from is missing here

2024-10-08 07:10 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +import { Avatar } '@momentum-design/components/react';
Done

2024-10-08 07:10 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +<script src="@momentum-design/components/browser/index.js"></script>
Done

2024-10-08 07:10 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +index.html
Done

2024-10-08 07:10 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +For detailed information about each component, refer to the [**Components Docs**](https://momentum-design.github.io/momentum-design/en/components/)
Done

2024-10-08 07:10 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +* Your build config needs to be able to have file loaders for CSS and WOFF.
Done

2024-10-08 07:10 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +In order to execute, run the following command:
Done

2024-10-08 07:11 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +* TypeScript > 4.7
Done

2024-10-08 07:11 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +This consumption guide for the Global Library, `@momentum-design/components` provides detailed instructions on how to effectively access and utilize these components in your web applications, specifi
Done

2024-10-08 07:11 UTC, 2020Deeya commented on packages/components/src/ConsumptionGuide.mdx
> +# Consumption Guide for Global web Library
Done

2024-10-08 07:12 UTC, 2020Deeya commented on packages/components/CONSUMPTION.md
> +# Consumption Guide for Global web Library
Yes, It's not needed.

2024-10-08 09:09 UTC, 2020Deeya commented on packages/components/src/Consumption.mdx
> +For detailed information about each component, refer to the [**indvidual**](https://momentum-design.github.io/momentum-design/en/components/)
Fixed it.

2024-10-08 13:39 UTC, cscheffauer approved these changes

2024-10-08 13:39 UTC, merged