Fix/components/theme provider/display mode
momentum-design/momentum-design pull request #878
Opened 2024-10-08 17:46 UTC by InteractiveTimmy

# Description

The scope of the changes in this pull request are to update the `display` of the `<mdc-themeprovider />` component to be `contents`, [which should be used for non-block-impacting components](https://developer.mozilla.org/en-US/docs/Web/CSS/display#contents).

Additionally, Stylesheet inheritance was being misrepresented from the `Provider` model into the `ThemeProvider` class definition.

Storybooks updated accordingly

# Links

* [Developer documentation on display contents]((https://developer.mozilla.org/en-US/docs/Web/CSS/display#contents).)

2024-10-08 18:07 UTC, chrisadubois approved these changes
lgtm, but would want @cscheffauer approval.

tests are also failing.

2024-10-08 18:07 UTC, chrisadubois commented on packages/components/src/components/themeprovider/themeprovider.component.ts
> +  public static override styles: Array<CSSResult> = [...Provider.styles, styles];
good catch

2024-10-08 18:07 UTC, chrisadubois commented on packages/components/src/models/provider/provider.component.ts
> +  public static override styles: Array<CSSResult> = [styles];
noice

2024-10-08 18:07 UTC, chrisadubois commented on packages/components/src/models/provider/provider.styles.ts
> +    display: contents;
👍

2024-10-10 11:43 UTC, cscheffauer requested changes

2024-10-10 11:43 UTC, cscheffauer commented on packages/components/src/components/iconprovider/iconprovider.styles.ts
> +const styles = css`
@Jason20020 this is against what Tim did with his change - why exactly did you need to set this? Where the screenshots off? or what is the impact if we don't set this style here?

2024-10-10 14:06 UTC, cscheffauer approved these changes

2024-10-10 14:06 UTC, merged