chore(component): update existing icon component
momentum-design/momentum-design pull request #879
Opened 2024-10-09 06:57 UTC by arjunkesava

# Description

- Update icons component to match with all the criteria as described on Icon tech [confluence](https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?pageId=562064947) page.
- Refactor dynamic SVG import code from promise pattern to async await pattern.
- Provide the option for consumers to add styles and classes.

| Before |
|---|
| <img width="1263" alt="image" src="https://github.com/user-attachments/assets/17e5ca2b-384f-40b7-9655-d2ff7b78ec5d"> |

| After |
|---|
| <img width="1263" alt="image" src="https://github.com/user-attachments/assets/8d9b3b5c-2062-4362-8e10-3c0c0cf8cd4e"> | 

The existing "Text" component is also not visible due to the white background which is set as a default.
This PR will add the "dark" background of gray color, due to which the text component can be visible.

## Links

JIRA ticket: [MOMENTUM-357](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-357)

2024-10-09 09:45 UTC, supminn submitted a review, later dismissed

2024-10-09 10:29 UTC, NotNestor commented on packages/components/src/components/icon/icon.component.ts
>   * @tagname mdc-icon
can we remove the @tag to fix the warnings. we should only use @tagname

2024-10-09 10:37 UTC, cscheffauer requested changes
first initial review, did not test locally yet - and also something additional:
All what we defined about css properties, styling etc is missing in this PR - please add.

2024-10-09 10:37 UTC, cscheffauer commented on packages/components/config/storybook/preview.js
> +      default: 'dark',
this is hard coding it to dark - we would want to set the background based on the theme. Use css overrides & see storybook for how to do this.

2024-10-09 10:37 UTC, cscheffauer commented on packages/components/src/components/icon/icon.component.ts
> + * - the `role` will always be 'img'.
issue: the role should not always be `img` - we discussed that in the breakdown. 
`aria-label` determines if a icon gets decorative or informative - only if the aria-label is set, we will set the role img.
This text here is not aligned with what we discussed.

2024-10-09 10:37 UTC, cscheffauer commented on packages/components/src/components/icon/icon.component.ts
>    private setRoleOnIcon() {
issue: this function should also be fired when the ariaLabel changes. For example if the icon is loaded and the aria-label changes afterwards, we want the role="img" to be set (or unset).

2024-10-09 10:37 UTC, cscheffauer commented on packages/components/src/components/icon/icon.component.ts
>        });
the console.error in line 134 has a warning - please put a eslint-ignore for this line to actively allow the console error here.

2024-10-09 10:37 UTC, cscheffauer commented on packages/components/src/components/icon/icon.stories.ts
> +    style: 'display: block;',
suggestion: to not confuse consumers, i would vote for a styling override which is less "impactful" and more obvious that its done through storybook, for example margin or so

2024-10-09 10:37 UTC, cscheffauer commented on packages/components/src/components/icon/icon.utils.ts
> +const dynamicSVGImport = async (url: string, name: string, fileExtension: string): Promise<Element> => {
nitpick: this function could benefit from a TSDoc

2024-10-09 10:37 UTC, cscheffauer commented on packages/components/src/components/icon/icon.stories.ts
> +const render = (args: Args) => html`
Nothing in storybook talks about decorative vs informative icons. We want our consumers to be able to understand when to use which.
I would recommend:
- Change story names to match Decorative / Informative
- Create additional documentation for Accessibility (a separate docs page in this components folder) to document Accessibility more thoroughly.

2024-10-10 09:04 UTC, arjunkesava commented on packages/components/src/components/icon/icon.component.ts
>        });
Done.

2024-10-10 16:30 UTC, cscheffauer requested changes

2024-10-10 16:30 UTC, cscheffauer commented on packages/components/src/components/icon/icon.stories.ts
> +    role: 'img',
issue: passing the role in here provides the user with wrong information. Role is not a attribute on the component and should also not be set by the user. Please remove this from here.

2024-10-10 16:30 UTC, cscheffauer commented on packages/components/src/components/icon/icon.component.ts
> + * In terms of `accessibility`, there are two types of icons, decorative and informative.
suggestion: to make this more clear i would vote for explicitly saying "if `aria-label` is passed in, the Icon will be a informative icon, otherwise its a decorative icon" or something like that. This way a consumer will understand it. With the description you have its not clear for a consumer that the aria-label actually determines if its a decorative icon or a informative icon.

2024-10-11 06:20 UTC, supminn commented on packages/components/src/components/icon/icon.component.ts
Overall, the documentation covers everything that is required. I have rephrased a few instances for better understanding. I hope this helps.

2024-10-11 11:23 UTC, cscheffauer approved these changes

2024-10-11 13:28 UTC, merged