test(pixelperfect):  pixel perfect on visual regression
momentum-design/momentum-design pull request #884
Opened 2024-10-10 14:23 UTC by Jason20020

# Description

***required*** - *Description of the changes made in this Pull Request*

## Links

***required*** - *Links to resources related to this Pull Request*

2024-10-16 10:30 UTC, cscheffauer requested changes

2024-10-16 10:30 UTC, cscheffauer commented on .github/workflows/pull-request.yml
> -            yarn workspace @momentum-design/components test:e2e:install
i think all of the changes here are not necessary and we just modify the scripts in the test:postbuild.
I can make the changes i was thinking of on your PR if you are fine with it.

2024-10-16 10:30 UTC, cscheffauer commented on .github/workflows/pull-request.yml
> +          run: |
same as above, those changes are not necessary

2024-10-16 10:30 UTC, cscheffauer commented on config/playwright/docker/Dockerfile.test.postbuild
> +FROM mcr.microsoft.com/playwright:v1.45.3-focal
i would recommend moving this into the components folder

2024-10-16 10:30 UTC, cscheffauer commented on config/playwright/docker/playwright.run.js
> +const { execSync } = require('child_process');
i would recommend moving this into the components folder

2024-10-16 10:30 UTC, cscheffauer commented on config/playwright/docker/Dockerfile.test.postbuild
> +RUN npm install -g corepack && corepack enable && corepack prepare yarn@3.2.4 --activate
suggestion: is it necessary to specify the yarn version here?
or can corepack pick that from the repo itself?
we do have the `.yarn` folder - maybe corepack picks the version up from there.
it would be good if we don't need to hardcode this here.

2024-10-16 10:30 UTC, cscheffauer commented on config/playwright/docker/playwright.run.js
> +    + `"yarn docker:install && yarn workspace ${workspace} ${scriptName}`;
if we move this util into components, we don't need to do the workspace anymore but just hardcode it to components for now. I think thats enough for now, we don't need docker in other packages yet and having this on the root makes it more complex to understand for the time being.

2024-10-16 10:30 UTC, cscheffauer commented on config/playwright/docker/playwright.run.js
> +  if (project) {
the script itself should be able to append that

2024-10-16 10:30 UTC, cscheffauer commented on package.json
> +    "docker:build": "docker build --platform linux/amd64 -f ./config/playwright/docker/Dockerfile.test.postbuild -t docker-test-postbuild .",
i would recommend to move this into the component folder to keep it scoped to components.

2024-10-16 10:30 UTC, cscheffauer commented on package.json
> +    "docker:install": "yarn install && yarn build && npx playwright install-deps && npx playwright install && npx playwright install chrome && npx playwright install msedge",
will this command run in the docker itself? its a bit confusing tbh.

2024-10-16 10:30 UTC, cscheffauer commented on packages/components/config/playwright/docker/playwright.docker.config.ts
> +import type { PlaywrightTestConfig } from '@playwright/test';
whats the difference between this and playwright.config.ts?
can we not just use playwright.config.ts?

2024-10-16 10:30 UTC, cscheffauer commented on packages/components/config/playwright/setup/constants.ts
> +  THRESHOLD: 0,
🥳  YESSSS - so good!

2024-10-16 10:30 UTC, cscheffauer commented on packages/components/config/playwright/setup/utils/visual-regression.ts
> +      _comparator: 'ssim-cie94' as any,
can u explain why this was necessary in a comment above?

2024-10-16 10:30 UTC, cscheffauer commented on packages/components/package.json
> +    "test:docker:postbuild": "yarn test:e2e:docker:all",
to follow convention, i think it would be `test:postbuild:docker`

2024-10-16 10:30 UTC, cscheffauer commented on packages/components/package.json
> +    "test:e2e:skip:snapshot": "E2E_SKIP_SNAPSHOT=true playwright test --config './config/playwright/playwright.config.ts'",
nitpick: in terms of naming we use the `:` to separate concern - so in this case `test:e2e:skip-snapshot` would make more sense.

2024-10-16 10:30 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.e2e-test.ts
> +const isSnapshotRun = process.env.E2E_SKIP_SNAPSHOT !== 'true';
suggestion: i would recommend to move this logic into the takeScreenshot utility.
having it here means you always have to write this line if a new e2e test is written.
applies for all tests

2024-10-16 11:09 UTC, 2020Deeya commented on README.md
> +- Supported Browsers:
Have we excluded Safari intentionally? If yes, I think, it'd be good if we add it's reasoning over here.

2024-10-16 11:13 UTC, 2020Deeya commented on package.json
> +    "docker:install": "yarn install && yarn build && npx playwright install-deps && npx playwright install && npx playwright install chrome && npx playwright install msedge",
Suggestion: The script looks too long, we could break this into two.

2024-10-16 12:28 UTC, cscheffauer commented on README.md
> +- Supported Browsers:
@2020Deeya Webkit = Safari

2024-10-16 15:15 UTC, Jason20020 commented on packages/components/config/playwright/setup/utils/visual-regression.ts
> +      _comparator: 'ssim-cie94' as any,
Just for testing before to fix the webkit, will delete

2024-10-25 13:56 UTC, cscheffauer approved these changes
great stuff! 💯

2024-10-25 13:57 UTC, merged