feat: text component updated
momentum-design/momentum-design pull request #891
Opened 2024-10-14 09:38 UTC by supminn

# Description

The text component has been updated based on the [Tech Breakdown](https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?pageId=563880910)

## Links

[MOMENTUM-365](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-365)

2024-10-14 09:44 UTC, supminn commented on packages/components/src/components/text/text.component.ts
> +    }
I wanted to create this section of the code as follows:
```html
 return html`<${this.tagname}><slot></slot></${this.tagname}>`
 ```
This is giving an error
Bindings cannot be used in place of tag names.
Template contained invalid HTML syntax, error was: invalid-first-character-of-tag-name

Alternatively, I worked on creating a utils function 
```javascript
import { html } from 'lit';
import { VALUES } from './text.constants';
import { ValidTextTags } from './text.types';

export function getTagNameTemplate(tagname: ValidTextTags | undefined): ReturnType<typeof html> {
  if (tagname && VALUES.TAGNAME.includes(tagname)) {
    // eslint-disable-next-line lit/binding-positions, lit/no-invalid-html
    return html`<${tagname}><slot></slot></${tagname}>`;
  }
  return html`<p><slot></slot></p>`;
}
```
But, this isn't helpful too. Let me know how I could improve this section of the code.

2024-10-14 09:48 UTC, supminn commented on packages/components/src/components/text/fonts.styles.ts
I've noticed that when we change the `tagname`, the default styles from user agent stylesheets are overriding our defined styles based on `type`.

2024-10-14 18:56 UTC, cscheffauer requested changes
first initial review, haven't tested locally yet

2024-10-14 18:56 UTC, cscheffauer commented on packages/components/src/components/text/text.component.ts
> +    switch (this.tagname) {
suggestion: this is a big switch case statement, include all of the html details. I would vote for replacing the tagname directly, like here: https://github.com/shoelace-style/shoelace/blob/next/src/components/button/button.component.ts#L264

2024-10-14 18:56 UTC, cscheffauer commented on packages/components/src/components/text/text.constants.ts
> +  TAGNAME: VALUES.TAGNAME[6],
issue: this has the potential to be broken, in particular if a new TagName gets added to the array.
Either use a object to keep track of the tagnames or hard code the value here - we shouldn't rely on array indexes given the potential to introduce a bug.

2024-10-16 09:55 UTC, supminn commented on packages/components/src/components/text/text.component.ts
> +    switch (this.tagname) {
We decided not to implement this change as per our discussion. We will continue to use switch case with hardcoded values to avoid using static-html from lit.

2024-10-16 22:42 UTC, cscheffauer submitted a review, later dismissed

2024-10-17 04:50 UTC, supminn commented on packages/components/src/components/text/text.component.ts
> +      console.error('Type attribute is required for mdc-text component');
Now that we are using a default value for type, I am getting this part of the code removed.

2024-10-17 04:51 UTC, supminn commented on packages/components/src/components/text/text.component.ts
> +  public type: FontType | null = null;
Sure, we can do this!
Since we want `type` to be a required attribute, I had set it to `null` and conditionally do not render the text component if `type` was not passed.

To keep it in-sync with how momentum-react does, I shall get the default value added. Thanks.

2024-10-18 07:44 UTC, arjunkesava approved these changes

2024-10-18 08:17 UTC, merged