chore(specs): write e2e specs for updated icon component
momentum-design/momentum-design pull request #893
Opened 2024-10-15 07:20 UTC by arjunkesava

# Description

- Add e2e specs for icon component.
- Always check for `aria-hidden` to true on SVG part of the icon component.
- Check `role` attribute to be set `img` when aria label is present.

## Links

<img width="525" alt="image" src="https://github.com/user-attachments/assets/f077f6ed-baec-4387-8de8-ddecae02b8df">

2024-10-15 14:20 UTC, cscheffauer requested changes
test case missing and a small comment, otherwise looking good.

2024-10-15 14:20 UTC, cscheffauer commented on packages/components/src/components/icon/icon.e2e-test.ts
> +    await test.step('attribute length unit should change the default size of em', async () => {
nitpick: this test name does not match what the test does.

2024-10-17 11:01 UTC, arjunkesava commented on packages/components/src/components/icon/icon.e2e-test.ts
>  test('mdc-icon', async ({ componentsPage }) => {
Done - eab5fad99d858a794b0c913ab47ee032aad722ba

2024-10-17 14:02 UTC, cscheffauer approved these changes

2024-10-17 14:35 UTC, merged