feat: add shared styles for focus ring
momentum-design/momentum-design pull request #899
Opened 2024-10-16 15:03 UTC by 2020Deeya

# Description

Add shared CSS styles for the focus ring

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-373

2024-10-17 13:00 UTC, arjunkesava submitted a review, later dismissed
Please attach a gif / movie / screenshot explaining the hover (i.e, focus) state of this new css.

2024-10-17 13:00 UTC, arjunkesava commented on packages/components/src/utils/styles/index.ts
> +  :host([focusRingVisible]) {
Q: can you help me explain how does this work?

The variable `focusRingVisible` is not imported from anywhere and neither declared anywhere aswell.

2024-10-17 13:24 UTC, cscheffauer submitted a review, later dismissed
code looks good to me - gonna test it in detail once we have a storybook

2024-10-18 18:25 UTC, 2020Deeya commented on packages/components/src/utils/styles/index.ts
> +  :host([focusRingVisible]) {
Please refer this PR related to Mixin. Styles will be applied to web-component when this attribute will be set to true by Mixin.
https://github.com/momentum-design/momentum-design/pull/901/

2024-10-21 07:37 UTC, supminn approved these changes
Good to merge if the updated color tokens are available.

2024-10-21 09:56 UTC, cscheffauer requested changes

2024-10-21 09:56 UTC, cscheffauer commented on packages/components/src/utils/styles/index.ts
> +    z-index: var(--mdc-focus-ring-z-index)
sorry for the confusion, i think the z-index here doesn't make sense - cause the host is our actual component itself (cause we use a mixin) - so in this case setting the z-index makes the whole component to have the z-index.
I think we actually don't need it - sorry for changing my point on this.

2024-10-21 09:56 UTC, cscheffauer commented on packages/components/src/utils/styles/index.ts
> +  :host(.focus-ring-visible) {
i have tried this in a codesandbox - everything looks fine, except for 2 particular cases:
- Try to set a "border" on the button or element you apply the focusRing to - in this case the positioning doesn't work. We have to consider this and work it out.
- I tried it on Firefox and the outline positioning doesn't work.
I have played around with it to see how to make it work better, and this is the solution i came up with:
```
content: "";
  position: absolute;
  top: 0;
  left: 0;
  right: 0;
  bottom: 0;
  outline: var(--mdc-focus-ring-middle-width) solid var(--mdc-focus-ring-middle-color);
  border-radius: inherit;
  outline-offset: var(--mdc-focus-ring-middle-offset);
```
In particular: set the top, left, right, bottom to 0 and use "outline-offset" instead

2024-10-21 11:48 UTC, cscheffauer requested changes

2024-10-21 11:48 UTC, cscheffauer commented on packages/components/src/utils/styles/index.ts
> +  :host(.focus-ring-visible) {
instead of a class, i think we can simply do this:
https://github.com/shoelace-style/shoelace/blob/next/src/components/button/button.styles.ts#L42
`:focus-visible` selector.
With that we wouldn't need the focus-ring-visible class logic, the protected property and also the consuming component can control it (by setting the "focus" programmatically on the component).

2024-10-22 07:55 UTC, 2020Deeya commented on packages/components/src/utils/styles/index.ts
> +    z-index: var(--mdc-focus-ring-z-index)
Agreed. 
Reverted it back.

2024-10-22 07:56 UTC, 2020Deeya commented on packages/components/src/utils/styles/index.ts
> +  :host(.focus-ring-visible) {
Yes, 
Also, Instead of set the top, left, right, bottom to 0, we could make use of inset property.

2024-10-22 07:58 UTC, 2020Deeya commented on packages/components/src/utils/styles/index.ts
> +  :host(.focus-ring-visible) {
Agreed. Fixed it.

2024-10-22 08:51 UTC, cscheffauer commented on packages/components/src/utils/styles/index.ts
> +  :host(.focus-ring-visible) {
issue: the first bullet point here has not been addressed, still an issue when setting the border on a element.

2024-10-23 14:05 UTC, 2020Deeya commented on packages/components/src/utils/styles/index.ts
> +  :host(.focus-ring-visible) {
There’s a limitation in our current logic for setting the border on an element. As an alternative, we will have to fall back on the box-shadow approach for now.

2024-10-23 15:06 UTC, cscheffauer requested changes

2024-10-23 15:06 UTC, cscheffauer commented on packages/components/src/utils/styles/index.ts
> +    --mdc-focus-ring-middle-width: calc(2 * var(--mdc-focus-ring-inner-width));
suggestion: i think here we would just do 0.125rem as well and on the other one the 0.0625rem, cause in the box-shadow we can do the offset, see comment below.

2024-10-23 15:06 UTC, cscheffauer commented on packages/components/src/utils/styles/index.ts
> +        0 0 0 var(--mdc-focus-ring-inner-width) var(--mdc-focus-ring-inner-color),
https://developer.mozilla.org/en-US/docs/Web/CSS/box-shadow
if u follow this, we can build it with proper offsets here (instead of 0 0 0).

2024-10-24 08:33 UTC, cscheffauer approved these changes

2024-10-24 08:42 UTC, merged