feat: High Contrast theme token updates
momentum-design/momentum-design pull request #903
Opened 2024-10-17 19:18 UTC by clairelikesemojis

# Description
[dark/light/hc_black/hc_white] New theme token added for focus ring effect: 
- color-theme-focus-0
- color-theme-focus-1
- color-theme-focus-2

## Links
https://www.figma.com/design/yYfvFEEr3UkW1yUKkW7zEH/%F0%9F%92%8E-Theme---Color?m=auto&node-id=0-1&t=eaX0SQnrEQqxXjj0-1

2024-10-17 20:41 UTC, cscheffauer requested changes

2024-10-17 20:41 UTC, cscheffauer commented on packages/assets/tokens/src/theme/stable/dark.json
> +                "space": "lch"
We need to test if this works in our tooling. @2020Deeya

2024-10-18 10:22 UTC, cscheffauer requested changes

2024-10-18 10:22 UTC, cscheffauer commented on packages/assets/tokens/src/theme/stable/light.json
> +          "value": "{color.core.black-alpha.100}",
@clairelikesemojis i think this is a bug - like in light theme i don't think this should be black-alpha? can u check please?

2024-10-21 16:19 UTC, clairelikesemojis commented on packages/assets/tokens/src/theme/stable/light.json
> +          "value": "{color.core.black-alpha.100}",
Yes! Just fixed it! Thanks

2024-10-21 17:24 UTC, cscheffauer approved these changes

2024-10-21 17:30 UTC, merged