feat(text): release text component
momentum-design/momentum-design pull request #911
Opened 2024-10-21 06:57 UTC by arjunkesava

# Description

Component "Text" is ready for consumption!
Text component is ready for consumption and considered stable.
See more details in [Storybook](https://momentum-design.github.io/momentum-design/en/components/).

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-371

2024-10-21 07:50 UTC, cscheffauer requested changes

2024-10-21 07:50 UTC, cscheffauer commented on packages/components/src/components/text/text.stories.ts
>  `;
@arjunkesava as discussed, this PR already makes the feat (minor version) bump for the text:
https://github.com/momentum-design/momentum-design/pull/891
We don't want another minor bump, thus in this case set "fix(text):" or something else in the PR Title.

2024-10-22 12:35 UTC, supminn approved these changes

2024-10-22 13:07 UTC, cscheffauer approved these changes

2024-10-22 13:07 UTC, merged