feat: add focus ring in storybook
momentum-design/momentum-design pull request #916
Opened 2024-10-23 11:40 UTC by 2020Deeya

# Description

Demonstrate focus ring behavior in different states (focus and blur) and on various elements.

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-375

2024-10-25 15:34 UTC, cscheffauer requested changes

2024-10-25 15:34 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.styles.ts
> +    :host {
<img width="567" alt="image" src="https://github.com/user-attachments/assets/50648f0c-d832-4726-9bca-6639ea2720f8">

I am very confused on this - first:
- why is there a orange border? is this to show that the focus works on borders?
- I just tried it in storybook and the focus ring doesn't show up currently on the button at all - not on the outside or anything. Can u please check this?

2024-10-25 15:34 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.constants.ts
> +  It is comprised of three distinct borders: black, blue, and light blue.
suggestion: we don't need to mention this in particular, cause this could be misleading. Like if we say 3 borders, thats not necessarily true cause we use box shadows - also for a consumer this information doesn't really matter i think.

2024-10-25 15:34 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.utils.ts
> +        return html`<a href="#" class="mds-anchor">LinkText</a>`;
issue: clicking on the link takes me out of storybook, i think this is not a great user behavior. I would vote for not having a href or so on the <a tag for now

2024-10-25 15:34 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.utils.ts
> +        return html`<div tabindex="0" class="mds-div">Focusable Div</div>`;
suggestion: i am not a big fan of this example, cause this is how components should NOT be built - like tabIndex=0 on a div is not accessible and has multiple issues. Not sure if we should show this here as a example.

2024-10-25 15:34 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.utils.ts
> +        return html`<input type="radio" id="radio" name="group" class="mds-radio" /><label for="radio"
issue: when i choose this type and focus to it, the focus ring shows on the radio inside, but not on the outside as i would expect. Or maybe the orange border here is making it misleading - maybe we can remove the orange border?
<img width="822" alt="image" src="https://github.com/user-attachments/assets/7b0c9b2c-6ec3-4891-bc28-466183167633">

2024-10-25 15:34 UTC, cscheffauer commented on packages/components/config/storybook/preview.js
>      },
issue on the PR title - this is not a feat, but maybe docs or something else?
we need to be careful in terms of deploying / naming the title if we want to follow a certain rythm in our release cadence.

2024-10-29 09:06 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.ts
> +import { FOCUS_RING_DESCRIPTION } from './subcomponent-focusring.constants';
Done.

2024-10-29 09:06 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.ts
> +    shape: SHAPES[0],
Done.

2024-10-29 09:12 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.styles.ts
> +    :host {
1] Orange border is there in order to consider a scenario what if a border is applied to web component and how it behaves in focus state.
2] Color Modifier is not being considered properly due to which focus ring is not showing up. I overlooked that change locally while performing unit conversion, and it was not pushed. 

Fixed it. Focus ring should now be visible.

2024-10-29 09:12 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.constants.ts
> +  It is comprised of three distinct borders: black, blue, and light blue.
Agreed. Removed it.

2024-10-29 09:19 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.utils.ts
> +        return html`<a href="#" class="mds-anchor">LinkText</a>`;
Removing the href attribute does not make the element focusable. Though, we could still make it work.
But I think, instead of removing href in anchor tag, we can show some another good example, ex: checkbox input

2024-10-29 09:19 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.utils.ts
> +        return html`<div tabindex="0" class="mds-div">Focusable Div</div>`;
okay, let's not show div as an example.

2024-10-29 09:22 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.utils.ts
> +        return html`<input type="radio" id="radio" name="group" class="mds-radio" /><label for="radio"
As I mentioned above, The orange border illustrates how a border applied to the web component behaves in the focus state. 

We could remove it for now to avoid confusion.

2024-10-29 09:34 UTC, 2020Deeya commented on packages/components/config/storybook/preview.js
>      },
Named it docs.

2024-10-29 14:11 UTC, cscheffauer requested changes

2024-10-29 14:11 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.styles.ts
> +      font-family: sans-serif;
nitpick: why setting the font-family here? no point in doing so given that we apply the font-family in the Themeprovider

2024-10-29 14:11 UTC, cscheffauer commented on packages/tools/token-builder/src/common/constants.ts
> +  COLOR_MODIFIER: 'ts/color/modifiers',
suggestion: i understand that this change is necessary - you have to put this information properly in the PR description. Worth keeping in mind that since you are making changes to both components and tokens, that there will be now 2 version bumps / releases, one for components, one for tokens.
My preference would be to put this token change in a separate PR, but if we keep it in this one, we at least need a proper description in the PR to reflect whats there.

2024-10-29 14:11 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.styles.ts
> +    :host {
issue: its like this now, which is also not correct - we want the "default" outline of the button etc to not be there, but just apply our own momentum focusring.
![image](https://github.com/user-attachments/assets/070d22fc-8586-4d3f-b171-6bf2375f39a5)

2024-10-29 14:11 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.styles.ts
> +    :host {
issue: also the select looks very confusing, like consumers will definitely not be able to understand what "our" focus ring is, vs the browser ones.
![image](https://github.com/user-attachments/assets/926d5e7b-022d-4ec0-97fb-0978843143dd)

2024-10-29 17:47 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.constants.ts
> +/* eslint-disable implicit-arrow-linebreak */
It can be removed now. It was added due to some old code. Thanks for pointing it out. Missed it.

2024-10-29 17:48 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.constants.ts
> +  SHAPE: 'mds-button' as const,
Since it's a temporary component, we've chosen this tagname temporarily. 
Yes, If we want, we can keep standards names.

2024-10-29 17:50 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.utils.ts
> + * The Focus Ring provides a visual indication of focus for users navigating via keyboard or mouse.
okay, Can we keep it like a comment? 
It was just to add short information about Focus ring.

2024-10-29 17:51 UTC, 2020Deeya commented on packages/components/src/stories/FocusRing/subcomponent-focusring.styles.ts
> +      font-family: sans-serif;
Sure. Removed it.

2024-10-29 18:05 UTC, 2020Deeya commented on packages/tools/token-builder/src/common/constants.ts
> +  COLOR_MODIFIER: 'ts/color/modifiers',
You're right! 
We should keep this change separate from this PR.

2024-10-30 09:29 UTC, cscheffauer approved these changes
one leftover comment which needs to be addressed, other than that looking good.

2024-10-30 09:29 UTC, cscheffauer commented on packages/components/src/stories/FocusRing/subcomponent-focusring.stories.ts
> +    shape: SHAPES[0],
this has not been addressed

2024-10-30 10:30 UTC, cscheffauer approved these changes

2024-10-30 10:30 UTC, merged