test(badge): e2e test for badge
momentum-design/momentum-design pull request #931
Opened 2024-11-01 12:23 UTC by Jason20020

# Description

create e2e test for badge component

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-383

2024-11-04 10:28 UTC, arjunkesava requested changes
Please rebase this branch and then resolve the comments.

2024-11-04 10:28 UTC, arjunkesava commented on packages/components/src/components/badge/badge.component.ts
> +        return this.getBadgeDot(overlay);
This is good. Instead of setting the `type` we can re-write this:
```typescript
  private getBadgeContentBasedOnType(): TemplateResult {
    const { counter, iconName, maxCounter, overlay, type, variant } = this;
    switch (type) {
 -
      case BADGE_TYPE.ICON:
        return this.getBadgeIcon(iconName || '', overlay, variant, type);
        ...
      case BADGE_TYPE.ERROR:
        return this.getBadgeIcon(ICON_NAMES_LIST.ERROR_ICON_NAME, overlay, ICON_STATE.ERROR);
+    case BADGE_TYPE.DOT:
+    default:
        return this.getBadgeDot(overlay);
    }
  }
 ```

2024-11-04 10:28 UTC, arjunkesava commented on packages/components/src/components/badge/badge.component.ts
> +    }
Please move this into `getBadgeIcon` method.
Currently, variant is used only on the icon type due to which changing it in the `getBadgeContentBasedOnType` is un-necessary.

2024-11-04 10:28 UTC, arjunkesava commented on packages/components/src/components/badge/badge.e2e-test.ts
> +      ${restArgs.ariaLabel ? `ariaLabel="${restArgs.ariaLabel}"` : ''}
HTML doesn't support camelCase attributes.
```suggestion
      ${restArgs.ariaLabel ? `aria-label="${restArgs.ariaLabel}"` : ''}
```

2024-11-04 11:20 UTC, cscheffauer requested changes

2024-11-04 14:23 UTC, Jason20020 commented on packages/components/src/components/badge/badge.component.ts
> +    }
I tried to move this into getBadgeIcon, but it will need to check are the ICON_STATE include, also changing the function parameter will get me error from analyze prebuild. It makes the code more complicated.

2024-11-05 06:02 UTC, arjunkesava approved these changes
LGTM.

2024-11-05 09:00 UTC, cscheffauer approved these changes

2024-11-05 10:37 UTC, merged