style(presence): styling for presence commponent
momentum-design/momentum-design pull request #939
Opened 2024-11-05 18:26 UTC by Jason20020

# Description

create presence component styling

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-395

2024-11-06 14:24 UTC, 2020Deeya submitted a review, later dismissed
LGTM

2024-11-06 15:14 UTC, cscheffauer requested changes

2024-11-06 15:14 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> +   * Size of the presence icon
suggestion: as a consumer i will not be aware of what the different sizes are, we should document them here

2024-11-06 15:14 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> + * Supported presence types:
this would be better suited in line 37

2024-11-06 15:14 UTC, cscheffauer commented on packages/components/src/components/presence/presence.constants.ts
> +  LENGTH_UNIT: 'rem',
issue: length_unit is not used

2024-11-06 15:14 UTC, cscheffauer commented on packages/components/src/components/presence/presence.styles.ts
> +      box-shadow: 0 0 0 0.129rem var(--mdc-presence-overlay-background-color);
issue: i think these rem values (all of them) are not correct. Like i can see different values in Figma for this.

2024-11-06 15:14 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> +  public override update(changedProperties: PropertyValues): void {
suggestion: this doesn't need to be here

2024-11-06 16:24 UTC, cscheffauer requested changes

2024-11-06 16:24 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> +   * Size of the presence icon in rem
issue: a user will not pass in the size in rem, so the way this is written is confusing in a way that it could mean that a consumer should pass in rem - but its really the different values. We also don't need to provide that table indicating how much each value is in REM - just put the acceptable values there on their own

2024-11-06 16:24 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> +        return 1.3;
issue: these might indicate that those are rounded values - we would want to be more accurate on those

2024-11-06 16:24 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> +  private get presenceSize() {
issue: this function isn't used anymore, can be removed

2024-11-07 11:25 UTC, cscheffauer requested changes
some small things to cleanup, rest looks good

2024-11-07 11:25 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> +  private getPresenceClasses(): { [key: string]: boolean } {
suggestion: this function can be avoided by putting this line directly in line 150, into the class map

2024-11-07 11:25 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> +  private getIconClasses(): { [key: string]: boolean } {
suggestion: this function can be avoided by putting this line directly in line 142, into the class map

2024-11-07 11:25 UTC, cscheffauer commented on packages/components/src/components/presence/presence.component.ts
> +  private getPresenceIcon(): TemplateResult {
suggestion: i think we can just inline this into line 150, like there is nothing too complex about the icon here for why we need that separate method.

2024-11-07 14:00 UTC, cscheffauer approved these changes

2024-11-07 14:00 UTC, merged