Feat/button comp
momentum-design/momentum-design pull request #948
Opened 2024-11-11 07:37 UTC by supminn

# Description
- Button component has 3 types:
  -  Pill button - Button that contains text value. It is commonly used for call to action, tags or filters.
  - Pill button with icons - Button containing icon either on the left or right side of the button. 
  - Icon button - Button is represented by just an icon without any text. 
- They have 3 variants - Primary, Secondary and Tertiary. 
- Different states a button can have are as follows: Active, Disabled, SoftDisabled (The button is currently disabled for user interaction; however, it remains focusable.)
- Colors:
  - Positive - Green button 
  - Negative - Red button 
  - Accent - Blue button 
  - Promotional - Purple button 
  - Default - Grey button 

We support the following sizes which vary based on the button type. As per our conventions guide, we shall use REM unit for button sizing.
- Pill button - 40, 32, 28, 24. 
- Icon button - 64, 52, 40, 32, 28 and 24.
    - Tertiary icon button can be of 20.
 
## Links
- [Tech Breakdown](https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?pageId=569871745)
- [Component and styling ticket](https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-386)

2024-11-11 11:58 UTC, arjunkesava requested changes

2024-11-11 11:58 UTC, arjunkesava commented on packages/components/src/components/button/button.component.ts
> + * @cssprop --custom-property-name - Description of the CSS custom property
```suggestion
 * @cssproperty --custom-property-name - Description of the CSS custom property
```

2024-11-11 11:58 UTC, arjunkesava commented on packages/components/src/components/button/button.component.ts
> +  @property({ type: Boolean }) disabled: boolean = false;
Q: If we assign a value to a type when declaration, do we need to still need to specify the type.
```suggestion
  @property({ type: Boolean }) disabled = false;
```

2024-11-11 11:58 UTC, arjunkesava commented on packages/components/src/components/button/button.component.ts
> +  private prevTabindex = 0;
This should be moved to the top of this page.

2024-11-11 11:58 UTC, arjunkesava commented on packages/components/src/components/button/button.component.ts
> +  }
This [article] suggests us to use javascript constructor for a single call events.
As the above events doesn't need to be re rendered / re attached again, we can follow this below approach:

```suggestion
  constructor() {
    super();
    this.role = 'button';
    this.handleButtonEvents();
  }

  private handleButtonEvents() {
    this.addEventListener('click', this.handleClick);
    this.addEventListener('keydown', this.handleKeyDown);
    this.addEventListener('keyup', this.handleKeyUp);
    this.addEventListener('focus', this.handleFocus);
    this.addEventListener('blur', this.handleBlur);
  }
```

Reg `removeEventListener`: we don't neeed to remove the events manually as JS will clean up when this component is no longer used.

2024-11-11 11:58 UTC, arjunkesava commented on packages/components/src/components/button/button.component.ts
> +  private prevIconName = '';
same here as well.

2024-11-11 11:58 UTC, arjunkesava commented on packages/components/src/components/button/button.utils.ts
> +    && !(size === 20 && variant !== 'tertiary');
```suggestion
    && !(size === 20 && variant !== BUTTON_VARIANTS.TERTIARY);
```
Always use constants instead of strings, whenever wherever possible.

2024-11-11 15:43 UTC, cscheffauer requested changes
initial review, haven't tested locally

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +    this.role = 'button';
issue: we should make this a property, like consumers should be able to override the role - therefore we want to make it a property

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +  public override connectedCallback() {
issue: eventlisteners need to be moved to constructor, as discussed here:
https://hawkticehurst.com/2023/11/you-are-probably-using-connectedcallback-wrong/

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +  private setAriaPressed(element: HTMLElement, active: boolean) {
issue: when a user passes in the attribute `aria-pressed` to the button (like controls it from the outside), this function will override it. Instead if a aria-pressed is passed in, we want that to take precidence.

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +  private setAriaLabel(element: HTMLElement, ariaLabel: string) {
issue: there is no point in having this function, since thats what the property declarator does automatically.

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      event.preventDefault();
question: why is the default prevented here when softDisabled?

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      event.preventDefault();
issue: why is the default prevented here?

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      this.classList.add('pressed');
issue: pressing enter or space should fire onclick!

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      if (children[0].nodeName === 'MDC-ICON') {
suggestion: hard coded values like MDC-ICON should always be set in constants. I think we can actually get the tagName constant from the icon component (import it from the constants file, thats important) and then we can do `toUppercase()` to make this string. This will make sure that in the future in case we change the tagName, we don't have to update this constant here.

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +    } else if (Array.from(children).some((node) => node.nodeName === 'MDC-ICON')) {
issue: what happens if there are 3 mdc-icons passed in? how will the button behave?

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      this.prevIconName = name;
issue: try to make a button active and then change the icon underneath, this will probably fail (haven't tried it though). My suggestion would be to just replace the suffix with `-filled` when active, otherwise just use the iconName of that node as it is.

2024-11-11 15:43 UTC, cscheffauer commented on packages/components/src/components/button/button.utils.ts
> +const isValidIconSize = (
this is only used once, no reason to put this in a utils function.
Its also easier to read if we keep it in inline. Same for the isValidPillSize

2024-11-12 05:47 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> +      this.classList.add('pressed');
Yes, onclick is invoked within `handleKeyUp`. Adding it here would invoke the onclick method when the user is pressing and holding the enter/space key.

2024-11-12 05:50 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> + * @cssprop --custom-property-name - Description of the CSS custom property
I have updated the docs section on https://github.com/supminn/momentum-design/pull/3 PR.

2024-11-12 05:55 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> +  }
Do we need to create `handleButtonEvents`?
Can't we directly add them into the constructor code?

2024-11-13 07:56 UTC, arjunkesava commented on packages/components/src/components/button/button.component.ts
> +  }
It's always better to keep the constructor clean.
My suggestion is to have a separate method to register all event listeners at one place.

2024-11-14 07:15 UTC, arjunkesava approved these changes
LGTM.

2024-11-14 07:15 UTC, arjunkesava commented on packages/components/src/components/button/button.component.ts
> +      : Object.values(PILL_BUTTON_SIZES).includes(size as PillButtonSize);
Suggestion: Please make this more readable. The logic is correct but due to multiple use of ternary operators, it becomes very tough to understand this snippet in one go.

2024-11-15 16:34 UTC, cscheffauer requested changes

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.stories.ts
> +    variant: BUTTON_VARIANTS.PRIMARY,
issue: when i toggle between primary, secondary and tertiary the size of the button changes - every variant should be of the same size.

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.stories.ts
> +const render = (args: Args) => html`
issue: tabIndex shows in storybook, but doesn't work. We either want it to work or we exclude it.

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +   * The role of the button.
suggestion: we should mention here when consumers should override the role. Its important that people are aware about this.

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.stories.ts
> +    ...classArgType,
![image](https://github.com/user-attachments/assets/10286d42-f938-4bf3-a2f2-1ecefb3c966a)
suggestion: i think if u add `@internal` in the tsdoc for all those private properties, they will not show up in storybook.

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +  @property({ type: String }) override role = 'button';
issue: role button doesn't show up by default - this component is not accessible!
![image](https://github.com/user-attachments/assets/b722f235-56bd-494d-9ea5-44f0b5aade79)

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +    if (!Object.values(BUTTON_VARIANTS).includes(variant)) {
suggestion: all these lines can be inlined too:
```javascript
this.setAttribute('variant', Object.values(BUTTON_VARIANTS).includes(variant) ? variant : DEFAULTS.VARIANT);
```

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      element.setAttribute('soft-disabled', 'true');
issue: this line is not necessary, cause soft-disabled is already set to true. same with line 288

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      element.setAttribute('disabled', 'true');
issue: same as above, you are setting the disabled attribute here again, it is already set. same for line 311

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      element.setAttribute('tabindex', `${this.tabIndex}`);
nitpick: `${}` is not necessary, you can do this.tabIndex directly

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +        this.onclick(event);
will the onClick event also be triggered cause of this or only the onclick method here?

2024-11-15 16:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +    const slot = event.target as HTMLSlotElement;
nitpick: this line is not necessary, we can pass event.target into the method directly

2024-11-15 17:19 UTC, cscheffauer commented on packages/components/src/components/button/button.styles.ts
> +`, hostFocusRingStyles];
actually was due to local setup, resolved

2024-11-18 05:48 UTC, 2020Deeya commented on packages/components/src/components/button/button.utils.ts
> +const getIconSize = (size: number): number => {
Suggestion:  Here, size is typed as number, but valid values are constrained by ICON_BUTTON_SIZES. A number type allows invalid input without compile-time error. We could use a union type if possible. 

type IconButtonSize = keyof typeof ICON_BUTTON_SIZES;
const getIconSize = (size: IconButtonSize): number => { ... }

2024-11-18 05:50 UTC, 2020Deeya commented on packages/components/src/components/button/button.utils.ts
> +  const variants = ['bold', 'filled', 'regular', 'light'];
Suggestion: Move variants to a shared constant outside of this function.

2024-11-18 05:52 UTC, 2020Deeya commented on packages/components/src/components/button/button.utils.ts
> +  const iconParts = iconName.split('-');
Question: Will there be any case when the icon name is empty or does not include a variant? If yes, we should handle it I think.

2024-11-18 05:54 UTC, 2020Deeya commented on packages/components/src/components/button/button.styles.ts
> +    border-radius: 6.25rem;
Suggestion: I see redundancy of border-radius property with same value. We could defined it on top and use that variable at all the places.

2024-11-18 06:59 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> +   * Indicates whether the button is active.
Could you help me out with this one? How can i elaborate on explaining this property?

2024-11-18 07:00 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> +      element.setAttribute('tabindex', `${this.tabIndex}`);
typescript was throwing an error to convert number to a string. Hence, I converted it into a template literal

2024-11-18 07:01 UTC, supminn commented on packages/components/src/components/button/button.utils.ts
> +  const variants = ['bold', 'filled', 'regular', 'light'];
these are constants pertaining to the icon names and not button. Hence, I added it within the function. They are not scoped outside this function.

2024-11-18 07:17 UTC, supminn commented on packages/components/src/components/button/button.utils.ts
> +  const iconParts = iconName.split('-');
As far as I understand, We support the list of icons from - https://momentum-design.github.io/momentum-design/en/tokens/icons/ 
I do not see any icon name without the variant.

2024-11-18 11:30 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> +      this.handleClick(event as unknown as MouseEvent);
thanks for this observation. It seems to be working in the same way across browsers. I have made necessary changes.

2024-11-18 11:37 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> +    } else if (Array.from(children).some((node) => node.nodeName === 'MDC-ICON')) {
With the structural changes (removing named slots and adding icon attributes), we no longer consider mdc-icon as an icon button if passed within the slot.
We do support 3 mdc-icons, but it would be called as a "pill-with-icon button"

2024-11-19 09:28 UTC, supminn commented on packages/components/src/components/button/button.stories.ts
> +  argTypes: {
Yes, this is no longer an icon button. It is 'pill-with-icon' button. The empty string is also consider as text.

2024-11-19 09:30 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> +      : Object.values(PILL_BUTTON_SIZES).includes(size as PillButtonSize);
I'm not sure on how we would achieve that. This is the simplest form I could add the logic in. I have added parenthesis around the condition. Let me know if that helps.

2024-11-19 09:31 UTC, supminn commented on packages/components/src/components/button/button.stories.ts
> +const render = (args: Args) => html`
Not sure why it's behaving in this way. The changes are reflecting when I update it directly on the tagname.
I have excluded it from storybook.

2024-11-27 10:33 UTC, arjunkesava approved these changes
LGTM.

One minor non-blocking comment.

2024-11-27 10:33 UTC, arjunkesava commented on packages/components/src/components/button/button.stories.ts
> +  },
Please set the default values on storybook, it becomes very tough to set a value as storybook will use string to object.

![image](https://github.com/user-attachments/assets/6d89d9eb-7310-4ff6-946a-6da6808147f5)

2024-11-27 11:40 UTC, arjunkesava approved these changes

2024-11-27 12:19 UTC, 2020Deeya commented on packages/components/src/components/button/button.styles.ts
> +    --mdc-button-line-height-size-24:  var(--mds-font-lineheight-body-small);
issue: Minor spacing issue, not a blocker one

2024-11-27 12:38 UTC, cscheffauer requested changes

2024-11-27 12:38 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +      element.setAttribute('tabindex', `${this.tabIndex}`);
suggestion: this can be made easier by using the reflect:true on the property, cause then u can just delete line 352 & 356.

2024-11-27 12:38 UTC, cscheffauer commented on packages/components/src/components/button/button.stories.ts
> +  type="${args.type}"
issue: role is not passed here.

2024-11-27 12:38 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> + * @slot default slot - Text label of the button.
issue: the default slot is wrong here, like this makes it actually a named slot from a docs perspective.
it should be `@slot - Text label ...`

2024-11-28 16:28 UTC, cscheffauer approved these changes

2024-11-28 16:28 UTC, merged