fix: add defaults in tsdoc
momentum-design/momentum-design pull request #951
Opened 2024-11-12 10:53 UTC by 2020Deeya

# Description

Add `@default` property in jsdoc to maintain readability across Storybook for consumers. 

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-407

2024-11-12 11:54 UTC, supminn requested changes

2024-11-12 11:54 UTC, supminn commented on packages/components/conventions/component-tsdoc.md
> +Usage: can be multiple
issue: we cannot have multiple default values.

2024-11-12 11:54 UTC, supminn commented on packages/components/src/components/iconprovider/iconprovider.component.ts
> +   * @default em
question (not related to docs): why do we have the default value as em and not rem?

2024-11-12 11:54 UTC, supminn commented on packages/components/src/components/iconprovider/iconprovider.constants.ts
> +  DEFAULT_SIZE: 1,
question: if we are adding a new property to DEFAULTS, do we still need to have `LENGTH_UNIT_SIZE` within the DEFAULTS object?

2024-11-12 11:54 UTC, supminn commented on packages/components/src/tsdoc.json
> +      "allowMultiple": true
issue: we cannot have multiple default values.

2024-11-12 11:55 UTC, 2020Deeya commented on packages/components/conventions/component-tsdoc.md
> +Usage: can be multiple
You're right, it got overlooked.

2024-11-12 12:01 UTC, 2020Deeya commented on packages/components/src/components/iconprovider/iconprovider.constants.ts
> +  DEFAULT_SIZE: 1,
I think, we should still keep it, because it defines default values for the units.

2024-11-12 13:20 UTC, supminn submitted a review, later dismissed

2024-11-13 05:17 UTC, supminn approved these changes

2024-11-13 05:17 UTC, merged