fix: update text component styling
momentum-design/momentum-design pull request #956
Opened 2024-11-14 09:16 UTC by 2020Deeya

# Description

Update text styles to make sure consumers can override the styles in the text component.

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-416

2024-11-14 14:24 UTC, cscheffauer requested changes
general issue: the expectation is that this PR doesn't change the screenshots at all

2024-11-14 14:24 UTC, cscheffauer commented on packages/components/src/components/text/fonts.styles.ts
> +    all: unset; /* This removes default styles applied by the browser */
issue: we should not override the browser defaults here if possible, if the browser has a default we should just keep it.

2024-11-14 14:37 UTC, 2020Deeya commented on packages/components/src/components/text/fonts.styles.ts
> +    all: unset; /* This removes default styles applied by the browser */
yes, Screenshots changes are temporary. They will be reverted back. It was to pushed to check something.

2024-11-15 13:04 UTC, 2020Deeya commented
Fresh PR is created instead of this. Hence, closing this one.

2024-11-15 13:04 UTC, closed without merging