test: create utility function for creating sticker sheet and reduce screenshots
momentum-design/momentum-design pull request #967
Opened 2024-11-21 15:30 UTC by Jason20020

# Description

- Create method that allow to create stickersheets on the page in e2e tests
- Reduce the amount of screenshots by using stickerSheet utility
## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-424
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-425

2024-11-22 10:32 UTC, Jason20020 commented on packages/components/src/components/icon/icon.types.ts
> +import type IconNames from '@momentum-design/icons/dist/types/types';
Using import type to prevent circular dependencies

2024-11-25 10:10 UTC, supminn requested changes
initial review - I pulled in the branch locally and found many linting issues.

2024-11-25 10:10 UTC, supminn commented on packages/components/config/playwright/setup/utils/visual-regression.ts
> +import { ComponentsPage } from '../../setup';
By importing `ComponentsPage` within this file, we are creating a cyclic link between this file and `Components.page.ts`
We would need to use this in a different way.

2024-11-25 12:45 UTC, 2020Deeya commented on packages/components/config/playwright/setup/utils/visual-regression.ts
>        await this.page.evaluate(() => {
Suggestion: Avoid Repetitive document.documentElement.setAttribute Calls and abstract this into a helper function.

2024-11-25 12:58 UTC, supminn requested changes

2024-11-25 12:58 UTC, supminn commented on packages/components/config/playwright/setup/utils/visual-regression.ts
> +      }
```suggestion
 for (const primaryValue of Object.values(primaryValues)) {
        const combinations = otherAttributes.reduce<string[]>(
          (acc, [key, values]) => {
            const valueArray = Object.values(values);
            return acc.flatMap((prev) =>
              valueArray.map((currVal) => `${prev} ${key}="${currVal}"`));
          },
          [''],
        );

        const rowMarkup = `<div class="componentRowWrapper">
          ${combinations.map((combination) => `<${componentTag} 
        ${primaryKey}="${primaryValue}"${combination}>${children}</${componentTag}>`).join('')}
        </div>`;

        markup += rowMarkup;
      }
```

suggestion: i think we could simply this for-loop as suggested.

2024-11-25 12:58 UTC, supminn commented on packages/components/config/playwright/setup/utils/visual-regression.ts
> +    children = '',
issue: Some of the components (ex: badge, icon) do not have `children`. Some other components might need to add a few attributes by default. Hence, I'd suggest you to make the following changes.
```
async createStickerSheet(
    componentsPage: ComponentsPage,
    componentTag: string,
    attributes: Record<string, Record<string, string>>,
    defaultAttributes?: Record<string, Record<string, string>>
)
```
Here, `defaultAttributes` could be defined as follows (i'm taking an example of the button component)
```
defaultAttributes:{
children: 'Label',
'prefix-icon': 'placeholder-bold'
}
```

2024-11-27 07:01 UTC, supminn requested changes
minor changes requested. Functionality looks good.

2024-11-27 07:20 UTC, supminn commented on packages/components/config/playwright/setup/utils/visual-regression.ts
>        await this.page.evaluate(() => {
handled on https://github.com/momentum-design/momentum-design/pull/971

2024-11-27 10:02 UTC, supminn approved these changes
LGTM

2024-11-27 10:03 UTC, merged