chore: avatar component and storybook
momentum-design/momentum-design pull request #972
Opened 2024-11-28 18:14 UTC by arjunkesava

# Description

- Build Avatar component based on Tech breakdown guidelines.
- This PR covers the Component and Storybook part of Avatar.

## Screenshots
![image](https://github.com/user-attachments/assets/a26051a6-68be-4a87-a0a7-5169d7d44a22)

2024-11-29 12:31 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +    const dimensions = this.generateAvatarDimensions();
Removed, moved this to CSS.

2024-11-29 12:31 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +    if (this.isPhotoLoaded) {
I would prefer to have this separate, as this is more readable.

2024-11-29 12:32 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +    const rems = [getAvatarSize(this.size), 'rem'].join('');
done. moved it to css.

2024-11-29 12:32 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
>          alt="${ifDefined(this.alt)}"
done. removed it.

2024-11-29 12:32 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +    throw new Error('There was a problem while fetching the <img/>. Please check the src attribute and try again.');
done, replaced it with `console.error` and added eslint disable for this line.

2024-11-29 12:33 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +    // while typing the loading spinner will be displayed and presence will be hidden
Removed this line, from now, presence will be shown when typing.

2024-11-29 12:37 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +          ${repeat(Array(3), () => html`
I've tried the mentioned css dots link above, the problem which I've faced is with the scaling.
the dots are not scalable for different size of avatars. Let me take another look at them.

2024-12-02 11:04 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +    throw new Error('There was a problem while fetching the <img/>. Please check the src attribute and try again.');
suggestion: as based on the latest convention, i think this one needs to be updated to have the this.onError handling

2024-12-03 06:33 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +    throw new Error('There was a problem while fetching the <img/>. Please check the src attribute and try again.');
done. via this commit: https://github.com/momentum-design/momentum-design/pull/972/commits/33da1baad45e350853e2b9328237ebb6b764ced2

2024-12-03 06:37 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +  isClickable = false;
Done. removed it via: https://github.com/momentum-design/momentum-design/pull/972/commits/3394d712de2aa36c63bb6af74371664405d83fc3

2024-12-03 08:36 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.utils.ts
> +const getAvatarLoadingScaleSize = (size: AvatarSize): string => {
Done. via https://github.com/momentum-design/momentum-design/pull/972/commits/6279a48657a2511ba0eae9f303952790e48af725

2024-12-03 08:36 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +          ${repeat(Array(3), () => html`
Done via https://github.com/momentum-design/momentum-design/pull/972/commits/6279a48657a2511ba0eae9f303952790e48af725

2024-12-04 08:24 UTC, supminn requested changes

2024-12-04 08:24 UTC, supminn commented on packages/components/src/components/avatar/avatar.component.ts
> +      return [MAX_COUNTER, '+'].join('');
nitpick: why not `${MAX_COUNTER}+` instead?

2024-12-04 08:24 UTC, supminn commented on packages/components/src/components/avatar/avatar.component.ts
> +   * Generates the loading spinner content for the avatar when typing.
suggestion: can we use the term 'loading indicator' rather than 'spinner'. As we show 3 dots, it doesn't justify to be spinner.

2024-12-04 08:24 UTC, supminn commented on packages/components/src/components/avatar/avatar.component.ts
> +    return nothing;
question: should we render nothing if photo is still loading and initials are not provided? 
suggestion: Would it be good to show the 'user-regular' icon instead? (as it is the default icon)

2024-12-04 08:24 UTC, supminn commented on packages/components/src/components/avatar/avatar.stories.ts
> +    },
issue: we need to define all the other args within `meta.argTypes`. Currently it is missing `src`, `counter`, `initial`, `icon-name`.
If we do not add them, any changes made to these args on storybook does not reflect on the component example.

2024-12-04 08:24 UTC, supminn commented on packages/components/src/components/avatar/avatar.stories.ts
> +};
question: if we are referring to this as the default avatar, I'd suggest that we use the same for fallback when the image is loading and initials are not provided 
default > initials > image

2024-12-04 11:41 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> + * we can show the initials text.
Initials are not mandatory. The default will be a `user-regular` icon.

2024-12-04 11:45 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +   * The avatar presence will be hidden if the user is typing or if the avatar type is counter.
The avatar presence will be hidden for counter type only.
For all other type of attributes, presence will be shown.

2024-12-04 11:47 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +      return [MAX_COUNTER, '+'].join('');
Both are valid, it's just that I prefer this approach. That's it.

2024-12-04 13:26 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +      return [MAX_COUNTER, '+'].join('');
issue: doing string concatenation as you mentioned Arjun is actually less performant than using ES6 Literals:
https://stackoverflow.com/a/29083467
You are correct in general that both are valid, but join is slower than ES6 Literals, so please change this to Supriya's suggestion and also use this moving forward.
This is a JS best practice, i think we don't need a convention for that.

2024-12-04 13:50 UTC, supminn commented on packages/components/src/components/avatar/avatar.component.ts
> +   * The avatar presence will be hidden if the user is typing or if the avatar type is counter.
sure. Could you please update the documentation. it says "The avatar presence will be hidden if the user is typing or if the avatar type is counter." currently.

2024-12-04 16:33 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +   * The avatar presence will be hidden if the user is typing or if the avatar type is counter.
Thanks for noticing it. I've updated it via https://github.com/momentum-design/momentum-design/pull/972/commits/70c0f69bee67b82856b6077fec58e87770f8c683

2024-12-04 16:33 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +      return [MAX_COUNTER, '+'].join('');
Done. I've updated it to template strings via https://github.com/momentum-design/momentum-design/pull/972/commits/70c0f69bee67b82856b6077fec58e87770f8c683

2024-12-06 05:24 UTC, supminn requested changes

2024-12-06 05:24 UTC, supminn commented on packages/components/src/components/avatar/avatar.stories.ts
> +};
```suggestion
export const Initials: StoryObj = {
 argTypes: {
    ...disableControls(['counter', 'icon-name']),
  },
  args: {
    initials: 'MD',
    size: 'xx_large',
  },
};
```

suggestion: can we restrict the attributes for specific avatar type examples. When I am testing them individual, it is causing confusion.
For example: On the 'Initial' story, we have an option to set counter. However, if I set the counter value, the avatar does not change to a counter type (it still remains as an text avatar).

2024-12-06 05:24 UTC, supminn commented on packages/components/src/components/avatar/avatar.stories.ts
> +};
The same restriction can be applied conditionally for each story component

2024-12-09 08:02 UTC, supminn requested changes

2024-12-09 08:02 UTC, supminn commented on packages/components/src/components/avatar/avatar.component.ts
> +    if (this.onclick) {
issue: While the onclick handler functions correctly when the button is clicked with a mouse, keyboard interactions using keydown and keyup events are not being recognized.

For instance, I expect the onclick handler defined on the avatar to be triggered both when the avatar is clicked with a mouse and when it is navigated to via keyboard. Currently, the keyboard interactions do not seem to be functioning as intended.

2024-12-09 09:55 UTC, cscheffauer requested changes

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.stories.ts
> +    'is-typing': false,
nitpick: is typing is by default false, so no need to set it here

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.stories.ts
> +export const Image: StoryObj = {
if u create a "Example" story as mentioned and I as a user can set the src on my own, this story is not needed anymore.

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +   * Aria-label attribute to be set for accessibility
issue: this aria-label will only be set for the Button (onclick is set) - we have to mention this here, otherwise consumers might be confused.

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.styles.ts
> +    --mdc-avatar-default-background-color: var(--mds-color-theme-avatar-default);
issue: the avatar is currently 612px wide (like the page) - we have to make sure that the element itself is just as big as the content. For that we have a utility called `hostFitContentStyles` - see Button component as an example.
![image](https://github.com/user-attachments/assets/b41fb3c2-37d0-4c31-a0e1-74ec30b17f28)

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.styles.ts
> +    cursor: pointer;
issue: this makes the whole Avatar to look like it can be clicked, but it can't - if i do not pass in onclick it still shows like this, which will be a User Experience issue cause users are expecting that something happens, but it doesn't.

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.styles.ts
> +    color: white;
suggestion: this is not correct and doesn't match the Figma spec. We always have to use our Theme tokens.
Use the same token for the loading animation then as well if possible.

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +   * @internal
nitpick: this method has `@internal` and the other private methods don't.
We want to be consistent, so please adjust.

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +    const typingBackgroundStyle = styleMap({ opacity: this.isTyping ? '.7' : '1' });
suggestion: as mentioned already, we should not need javascript to style if its based on a attribute - please move this into the stylesheet.

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.stories.ts
> +  <mdc-avatar
issue(a11y): if i put a aria-label onto a clickable button and use the screenreader, it will read `aria-label, aria-label, group`, which is ultimately wrong. This Avatar is not a group, but supposed to be a button.
We have to fix this.

2024-12-09 09:55 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.stories.ts
> +    ?is-typing="${args['is-typing']}"
issue: i did pass in an `id` attribute and connected a label to this avatar (`<label for="avatar">test</label>`) - normally if a label is connected to a button and you click on the label, it should click the button. In this case it doesn't, since i think that the `label` can't find the button. I also tried passing the `id` to the mdc-button, its also not working - i think that has something to do with how shadow dom works, like it can't pierce through the shadow dom.
This is where u did the investigation on at the very beginning for the avatar - host-aria vs delegate aria. In this case i have a feeling we need to refactor the component to be host-aria, as suggested earlier.

2024-12-10 21:51 UTC, cscheffauer requested changes

2024-12-10 21:51 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +  private renderedContent(): TemplateResult {
suggestion: this function is not necessary, can be put into the render directly. this will avoid one function call and reduces the code lines in this file. also readability will not suffer, since its very good structured.

2024-12-10 21:51 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.stories.ts
> +export const Image: StoryObj = {
this is not addressed, now there are both Example and Image story - also make sure that the `Example` is always the first one - check this PR for the exact convention:
https://github.com/momentum-design/momentum-design/pull/987/files#diff-39335bf37c23b757ff30a6782f5c4f7d2aff9421c9847b6167252124194b396dR3

2024-12-10 21:51 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
>        <img
issue: currently when i do turn Chrome Network Emulation to "Slow 4G" and i paste the src and remove it again (see below), it removes the initials and then a while after shows the image. This will be a flicker for the user. We have to fix this.

https://github.com/user-attachments/assets/6d44912b-7889-487d-a651-3569b0b92252

2024-12-10 21:51 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
>        <img
this also happens if there is a different fallback:

https://github.com/user-attachments/assets/237c6ed3-3790-4b8d-949c-619e49fb59aa

2024-12-10 21:51 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +  private iconTemplate(): TemplateResult {
issue: this is not only an issue on the img, but also when the Icon Template is loaded or when we fall back to the "user-regular" icon. To fix this, we probably want a custom event in the Icon to indicate that its loaded (or a onload method similar to the img), which we can then hook into and have another internal state (same as img) which we can then use to only render the icon once its actually downloaded.

https://github.com/user-attachments/assets/d9db24ce-e9b6-4f39-a490-5de70ba1d9a2

2024-12-10 21:51 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +  private textTemplate(content: string): TemplateResult {
suggestion: general note, we discussed that we are building the ButtonAvatar component after this component, but the code here is not prepared to allow for that. Like once u build the ButtonAvatar component my expectation is that u reuse the existing code from here (which is currently not possible). So we have to abstract our styling which we share into separate styles and also our templating which is happening here and probably logic.
For that i think we should look into making use of Mixins or Controllers (see lit.dev)

2024-12-10 21:51 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +  counter?: number;
issue: when passing in `0` (zero) into the counter, it doesn't render it:
![image](https://github.com/user-attachments/assets/b9deb919-eefe-4b51-89b3-61f5264dab6b)

2024-12-12 07:44 UTC, 2020Deeya commented on packages/components/src/components/avatar/avatar.utils.ts
> +};
suggestion: The switch cases in both functions have repetitive logic. These can be replaced by a mapping object for better maintainability.

2024-12-12 07:49 UTC, 2020Deeya commented on packages/components/src/components/avatar/avatar.component.ts
>   */
question: I see, CSS variables have been used in styling, should we not mentioned them over here?

2024-12-12 07:53 UTC, 2020Deeya commented on packages/components/src/components/avatar/avatar.component.ts
> +    if (type === AVATAR_TYPE.COUNTER && this.counter) {
issue: Here, this.counter can also have 0 value where it'll return nothing, which is not expected. Logic should be refactored w.r.t using this.counter.

2024-12-12 09:18 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +  private iconTemplate(): TemplateResult {
this is not resolved

2024-12-12 09:22 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +    if (type === AVATAR_TYPE.COUNTER && this.counter) {
agreed, presence gets rendered when 0 is set:
![image](https://github.com/user-attachments/assets/4e7d94c9-91c6-4998-bf50-608f40e60cca)

2024-12-12 09:29 UTC, cscheffauer requested changes

2024-12-12 09:29 UTC, cscheffauer commented on packages/components/src/components/avatar/avatar.component.ts
> +      this.isPhotoLoaded = false;
issue: this is causing this behavior now:
When you change the src, it will go back to the initials, then jump to the new image. The expected behavior is that when the src changes that the existing src image stays until the new src is loaded.
Momentum React v2 does this as well, maybe check it there.

https://github.com/user-attachments/assets/07bfaa58-4396-40a0-aefa-7285d8898f82

2024-12-12 17:09 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +      this.isPhotoLoaded = false;
This issue is fixed via https://github.com/momentum-design/momentum-design/pull/972/commits/9efd8986b729366e4beb474d582a6bf6514da29a,
We will now reset the photo loaded state when the src attribute is empty.

2024-12-12 17:09 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +    if (type === AVATAR_TYPE.COUNTER && this.counter) {
Fixed.

2024-12-12 17:09 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
>   */
Fixed.

2024-12-12 17:10 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.utils.ts
> +};
Fixed.

2024-12-12 17:16 UTC, arjunkesava commented on packages/components/src/components/avatar/avatar.component.ts
> +  private iconTemplate(): TemplateResult {
created a new ticket to solve this issue: https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-454

2024-12-13 08:41 UTC, 2020Deeya commented on packages/components/src/components/avatar/avatar.component.ts
>   */
I still don't see CSS variables defined here in component file.

2024-12-13 09:36 UTC, cscheffauer approved these changes

2024-12-13 10:41 UTC, supminn reviewed
documentation update required.

2024-12-13 11:07 UTC, supminn approved these changes

2024-12-13 11:11 UTC, 2020Deeya approved these changes
LGTM

2024-12-13 11:20 UTC, merged