Add Marker Component
momentum-design/momentum-design pull request #976
Opened 2024-11-29 18:47 UTC by sandgupta23

Implemented a new Marker Component.

# Description

Implemented a new Marker Component.

## Links

Spec:
[_Please replace this line with relevant links to the changes made in this Pull Request._](https://confluence-eng-gpk2.cisco.com/conf/pages/viewpage.action?pageId=591008598)

Figma:
https://www.figma.com/design/9qhjTsC97Q3W8ZsbnTiZho/%F0%9F%A7%A9-%5BWIP%5D-Momentum-Web-Library?node-id=19902-33835&node-type=instance&m=dev

2024-12-02 10:29 UTC, cscheffauer requested changes

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.component.ts
> +type MarkerChangedProperties = Map<keyof Marker, Marker[keyof Marker]>;
suggestion: types should be moved into the types file (following our convention here: https://github.com/momentum-design/momentum-design/blob/main/packages/components/conventions/component-code-structure.md)

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.component.ts
> + * @slot default - This is a default/unnamed slot
issue: this is not applicable (same as the cssprop below), please clean up!

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.component.ts
> +  @property({ type: String }) variant: MarkerVariant = MARKER_VARIANTS.SOLID;
issue: according to our conventions we should document every public property (adding TSDoc) - see here:
https://github.com/momentum-design/momentum-design/blob/main/packages/components/conventions/component-tsdoc.md#attributes--properties--methods-block

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.component.ts
> +    this.classList.add(MARKER_VARIANTS_CLASS_MAPPING[this.variant]);
issue: using javascript to change the styling here is an issue, like causes an performance issue. You can remove lines 25 to 41 completely and do the styling in the css file directly.

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.constants.ts
> +type MarkerVariant = keyof typeof MARKER_VARIANTS;
suggestion: we should not mix constants and types, put the types in the types file and the constants in here.

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.constants.ts
> +    "SOLID": "mdc-marker--solid",
issue: your local setup is not correct, like i see a ton of eslint & typescript issues in all your files. Please make sure to install the right VS Code extensions (ESLint) - will create a section in our guides for that.

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.constants.ts
> +const MARKER_VARIANTS_CLASS_MAPPING = {
suggestion: this is not necessary if u follow the CSS styling approach (see other comments)

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.stories.ts
> +export const solid: StoryObj = {
suggestion: those Story names should be Uppercase, see other components.

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.stories.ts
> +export const striped: StoryObj = {
i think we might not need multiple stories, but just have a single one "Example" and there we just put the variant as a dropdown (see other components on how to do this)

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.styles.ts
> +const SOLID_CLASS_NAME_BYPASS = unsafeCSS(MARKER_CLASSES.SOLID);
issue: this is not necessary, please check other components like this one:
https://github.com/momentum-design/momentum-design/blob/main/packages/components/src/components/button/button.styles.ts#L52
you can directly do `:host([variant="striped"]){` - no need to create separate classes or such.

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.styles.ts
> +    display: inline-block;
question: is inline-block necessary or can it also work with a normal block?

2024-12-02 10:29 UTC, cscheffauer commented on packages/components/src/components/marker/marker.styles.ts
> +    background: var(--mds-color-theme-outline-secondary-normal, rgba(0, 0, 0, 0.20));
suggestion: i would recommend to abstract the color here out to a component css variable, see:
https://github.com/momentum-design/momentum-design/blob/main/packages/components/conventions/component-styles-variables.md
the same variable can then be used in line 21,22

2024-12-03 10:12 UTC, sandgupta23 commented on packages/components/src/components/marker/marker.component.ts
> +type MarkerChangedProperties = Map<keyof Marker, Marker[keyof Marker]>;
Fixed.

2024-12-03 10:12 UTC, sandgupta23 commented on packages/components/src/components/marker/marker.component.ts
> + * @slot default - This is a default/unnamed slot
Fixed.

2024-12-03 10:12 UTC, sandgupta23 commented on packages/components/src/components/marker/marker.component.ts
> +    this.classList.add(MARKER_VARIANTS_CLASS_MAPPING[this.variant]);
Fixed.

2024-12-03 10:13 UTC, sandgupta23 commented on packages/components/src/components/marker/marker.stories.ts
> +export const solid: StoryObj = {
Fixed.

2024-12-03 13:14 UTC, sandgupta23 commented on packages/components/src/components/marker/marker.stories.ts
> +export const striped: StoryObj = {
Fixed

2024-12-03 13:16 UTC, sandgupta23 commented on packages/components/src/components/marker/marker.styles.ts
> +    display: inline-block;
By default lit comp are display: inline. In order for height to work we need display: block/inline-block/flex etc.

2024-12-03 13:17 UTC, sandgupta23 commented on packages/components/src/components/marker/marker.styles.ts
> +    background: var(--mds-color-theme-outline-secondary-normal, rgba(0, 0, 0, 0.20));
fixed

2024-12-05 10:31 UTC, 2020Deeya commented on packages/components/src/components/marker/marker.styles.ts
> +      var(--mdc-marker-striped-color, rgba(0, 0, 0, 0.20)),
Issue: We should not provide any fallback values because color can vary depending upon the curremt theme.

2024-12-16 11:39 UTC, cscheffauer requested changes

2024-12-16 11:39 UTC, cscheffauer commented on packages/components/src/components/marker/marker.e2e-test.ts
> +test.describe.parallel('mdc-Marker', () => {
suggestion: this is not necessary at all, like there is only one test

2024-12-16 11:39 UTC, cscheffauer commented on packages/components/src/components/marker/marker.e2e-test.ts
> +    const container = stickerSheet.getWrapperContainer();
issue: something is broken, cause all the screenshots you created are completely white, like nothing is shown.
Please verify the screenshots, not just create them without looking at them.

2024-12-17 05:14 UTC, supminn commented on packages/components/src/components/marker/marker.e2e-test.ts
> +    const container = stickerSheet.getWrapperContainer();
```suggestion
 await stickerSheet.mountComponents({ variant: MARKER_VARIANTS });
    const container = stickerSheet.getWrapperContainer();
    await container.evaluate((el) => {
      const wrapper = el.querySelector('.componentRowWrapper') as HTMLElement;
      wrapper.style.height = '100px';
    });
    
   These suggested changes will fix the snapshots. As the height of the marker depends on the container, it is necessary to set a fixed height for the wrapper container.
    
    
```

2024-12-17 05:52 UTC, 2020Deeya commented on packages/components/src/components/marker/marker.styles.ts
> +    --mdc-marker-striped-background-color: transparent;
nitpick: We could keep CSS custom variables on top for better readability purpose.

2024-12-17 05:54 UTC, 2020Deeya commented on packages/components/src/components/marker/marker.styles.ts
> +    width: 0.25rem;
issue: We should allow consumers to override the Marker's width if they wish to. To achieve that, we should create a CSS variable for Marker's width.

2024-12-17 08:13 UTC, supminn commented on packages/components/src/components/marker/marker.styles.ts
> +    width: 0.25rem;
@2020Deeya Do we allow width to be modified? This is not mentioned on the tech breakdown.

2024-12-17 08:25 UTC, cscheffauer approved these changes

2024-12-17 08:58 UTC, 2020Deeya commented on packages/components/src/components/marker/marker.styles.ts
> +    width: 0.25rem;
@supminn , Yes, Width can be overridden, it's mentioned in the tech breakdown.

2024-12-19 17:32 UTC, cscheffauer approved these changes

2024-12-19 17:33 UTC, merged