docs: Implement Divider Component
momentum-design/momentum-design pull request #978
Opened 2024-12-03 12:19 UTC by 2020Deeya

# Description

Create Divider Component and Storybook docs

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-432
https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-433

2024-12-12 09:50 UTC, supminn requested changes

2024-12-12 09:50 UTC, supminn commented on packages/components/src/components/divider/divider.component.ts
> +    buttonElement.setAttribute('aria-expanded', this.ariaExpanded || '');
issue: we should not set it to an empty string. The default value would automatically be taken when user hasn't set it right?

2024-12-12 09:50 UTC, supminn commented on packages/components/src/components/divider/divider.component.ts
> +  }
issue: since we are setting class names on the component, it is treated similar to having classes on an HTML element. The consumers have an option to remove these classes. Thus, we shouldn't depend on class names for our component logic.
suggestion: We can make use of data attributes. Setting data attributes on the element itself can be helpful. We can further use this attributes for styling.

```suggestion
  private setClassBasedOnType(type: string) {
    if (type === DIVIDER_TYPE_INTERNAL.PRIMARY) {
      this.setAttribute('data-type','mdc-primary-divider');
    } else if (type === DIVIDER_TYPE_INTERNAL.TEXT) {
        this.setAttribute('data-type','mdc-text-divider');
    } else if (type === DIVIDER_TYPE_INTERNAL.GRABBER_BUTTON) {
      this.setAttribute('data-type','mdc-grabber-divider');
    }
  }
```

On the styles file, you can use them just like any other attribute
```
:host([data-type='mdc-text-divider']){
// styles
}
```

2024-12-12 09:50 UTC, supminn commented on packages/components/src/components/divider/divider.component.ts
> +    const hasButtonChild = assignedElements.some((el) => el.tagName === 'MDC-BUTTON');
suggestion: we can make use of the `TAGNAME` constants from button and text instead of hard coding these values.

2024-12-12 09:50 UTC, supminn commented on packages/components/src/components/divider/divider.component.ts
> +    this.setVariant(this.variant);
question: why do we need to invoke them here?

2024-12-12 10:05 UTC, 2020Deeya commented on packages/components/src/components/divider/divider.component.ts
> + * - **Vertical**: A thin, vertical line with 0.063rem width.
ya, it should be 0.0625rem. Correcting it.
I think, it should be mentioned over here as well.

2024-12-12 10:08 UTC, 2020Deeya commented on packages/components/src/components/divider/divider.component.ts
> +    const hasButtonChild = assignedElements.some((el) => el.tagName === 'MDC-BUTTON');
Sure, we can. I left it to get suggestions from everyone if it's actually required.

2024-12-12 10:10 UTC, 2020Deeya commented on packages/components/src/components/divider/divider.component.ts
> +    buttonElement.setAttribute('aria-expanded', this.ariaExpanded || '');
Do you mean, the default value of button? 
If that's the case, we can remove the empty string.

2024-12-12 10:16 UTC, supminn commented on packages/components/src/components/divider/divider.component.ts
> + * - **Vertical**: A thin, vertical line with 0.063rem width.
It's mentioned on the docs above the property. So, i'm not sure if it adds value here.

2024-12-12 11:42 UTC, 2020Deeya commented on packages/components/src/components/divider/divider.component.ts
> + * - **Vertical**: A thin, vertical line with 0.063rem width.
Fair enough.

2024-12-16 06:46 UTC, supminn requested changes

2024-12-16 06:46 UTC, supminn commented on packages/components/src/components/divider/divider.stories.ts
> +      description: 'Only horizontal orientation with 0.0625rem width is allowed',
suggestion:

>  Note: We do not support "Vertical Text Divider" as of now.

This note is shown on all the other stories except this one. I'd suggest you to add this note here as well.

2024-12-16 06:46 UTC, supminn commented on packages/components/src/components/divider/divider.component.ts
> +    const defaultDirection = this.orientation === DIVIDER_ORIENTATION.HORIZONTAL ? DIRECTIONS.NEGATIVE : DIRECTIONS.POSITIVE;
```suggestion
    const defaultDirection = this.orientation === DIVIDER_ORIENTATION.HORIZONTAL
      ? DIRECTIONS.NEGATIVE
      : DIRECTIONS.POSITIVE;
```
By doing this, we can avoid using eslint-disabled.

2024-12-16 10:04 UTC, 2020Deeya commented on packages/components/src/components/divider/divider.component.ts
> +    const defaultDirection = this.orientation === DIVIDER_ORIENTATION.HORIZONTAL ? DIRECTIONS.NEGATIVE : DIRECTIONS.POSITIVE;
Done

2024-12-16 11:33 UTC, supminn requested changes

2024-12-16 11:33 UTC, supminn commented on packages/components/src/components/divider/divider.component.ts
> +    this.observer = new MutationObserver(() => this.handleWindowDirectionChange());
issue: this shouldn't be used. MutationObserver is an expensive call. We should avoid using this and make changes using css styling instead.

2024-12-16 11:33 UTC, supminn commented on packages/components/src/components/divider/divider.component.ts
> +  /** @internal */
suggestion: We can omit using this internal state as we are capturing `data-type` to infer the type of divider.

2024-12-17 09:44 UTC, supminn approved these changes
LGTM

2024-12-17 09:46 UTC, 2020Deeya commented on packages/components/src/components/divider/divider.component.ts
> +    this.observer = new MutationObserver(() => this.handleWindowDirectionChange());
Fixed.

2024-12-17 09:57 UTC, merged