test: e2e test cases for button component
momentum-design/momentum-design pull request #980
Opened 2024-12-04 07:16 UTC by supminn

# Description
This PR covers the end to end test cases for button component along with accessibility checks as well as visual regression snapshot testing.

## Links

https://jira-eng-gpk2.cisco.com/jira/browse/MOMENTUM-388

2024-12-10 15:54 UTC, cscheffauer requested changes

2024-12-10 15:54 UTC, cscheffauer commented on packages/components/src/components/button/button.e2e-test.ts
> +  test('mdc-button key pressed and focused events', async ({ componentsPage }) => {
issue: in none of these tests the "onclick" method on the button is verified. We have to test that as well.
I would recommend to just do the same assertion in the already existing tests, lets not create another one.

2024-12-10 15:54 UTC, cscheffauer commented on packages/components/src/components/button/button.e2e-test.ts
> +  test('mdc-button click event', async ({ componentsPage }) => {
suggestion: you are using `test` very often - what that does is that everytime you do `test`, it opens a new browser window - thats very resource heavy - i would recommend to combine tests together, use the test.step more often.
With that u don't need to the mount all the time, but just keep one button there, change the attributes of the button and assert again. With that the overall runtime of this test file should be reduced.

2024-12-10 15:54 UTC, cscheffauer commented on packages/components/src/components/button/button.styles.ts
> +    padding: 0.0625rem;
q: was that missed? or why are we adding this now? this is in the actual component, just want to confirm.

2024-12-10 15:54 UTC, cscheffauer commented on packages/components/src/components/icon/icon.component.ts
> +          console.error('Fetch error:', err);
suggestion: since you are making changes here, i would recommend to not console.error, but do the onerror callback, as mentioned in our newly created error handling convention.

2024-12-10 15:54 UTC, cscheffauer commented on packages/components/src/components/icon/icon.utils.ts
> +const dynamicSVGImport = async (
i think it would be neat to document how the signal works (or at least link to the lit.dev page) in this TSDoc.

2024-12-10 15:54 UTC, cscheffauer commented on packages/components/src/components/icon/icon.component.ts
> +        this.abortController = new AbortController();
q: why do we need to create another instance of the abortController? i think this is not necessary and might also cause issues in terms of constantly initialising another controller.

2024-12-10 15:54 UTC, cscheffauer commented on packages/components/src/components/icon/icon.component.ts
> +    this.abortController = new AbortController(); // Initialize AbortController
praise: for adding this, this is very neat!

2024-12-11 04:20 UTC, supminn commented on packages/components/src/components/button/button.component.ts
> +        this.getAttribute('aria-label') || this.prefixIcon || this.postfixIcon || BUTTON_TYPE_INTERNAL.ICON,
I agree. I had initially not added this attribute. However, the a11y test case failed due to its absence. Do I need to pass aria-label from my test case instance?

2024-12-11 04:21 UTC, supminn commented on packages/components/src/components/button/button.e2e-test.ts
> +  test('mdc-button click event', async ({ componentsPage }) => {
Thank you for sharing this valuable information. I'll make the necessary changes.

2024-12-11 04:22 UTC, supminn commented on packages/components/src/components/button/button.styles.ts
> +    padding: 0.0625rem;
yes, we seem to have missed it during the component development. I figured it out while having a discussion with Jason over the popover close button.

2024-12-11 04:23 UTC, supminn commented on packages/components/src/components/icon/icon.component.ts
> +        this.abortController = new AbortController();
yes, this is necessary. If we reuse the same AbortController instance and call abort() after starting a new fetch, it will terminate the previous fetch as well as the new one.

2024-12-11 04:23 UTC, supminn commented on packages/components/src/components/icon/icon.component.ts
> +    this.abortController = new AbortController(); // Initialize AbortController
Thank you!

2024-12-11 04:32 UTC, supminn commented on packages/components/src/components/icon/icon.utils.ts
> +const dynamicSVGImport = async (
Sure, I've got this added. I shall share about this during our learning session too.

2024-12-11 14:22 UTC, cscheffauer commented on packages/components/src/components/icon/icon.component.ts
> +        this.abortController = new AbortController();
just checked, it seems to be fine in terms of cleanup - i was thinking that its actually an issue, since we don't cleanup - it seems `.abort()` is somehow already the cleanup.

2024-12-12 07:12 UTC, 2020Deeya commented on packages/components/src/components/button/button.component.ts
> -  private setClassBasedOnType(type: string) {
question: Could you explain what was the issue which made us to switch our class logic to setting attribute?

2024-12-13 08:47 UTC, supminn commented
Closing this PR has it has bloated the number of commits. Created https://github.com/momentum-design/momentum-design/pull/994 with necessary changes.

2024-12-13 08:47 UTC, closed without merging