chore: build button avatar component
momentum-design/momentum-design pull request #999
Opened 2024-12-17 10:46 UTC by arjunkesava

# Description

- Build an clickable avatar with button as a wrapper.
- This button avatar component uses the same attributes which are used in avatar component.
- All of the business logic will be the same for Avatar and this component.
- Create a new mixin: AvatarComponentMixin to inherit common props in between both Avatar and ButtonAvatar components.

<img width="868" alt="image" src="https://github.com/user-attachments/assets/21c32643-f0d1-4e4d-b390-82750679aaa6" />

2024-12-17 13:34 UTC, cscheffauer requested changes
first round of review, multiple issues

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +import { AvatarSize } from '../avatar/avatar.types';
suggestion: follow our convention of making this a type only import

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.component.ts
> + * @dependecy mdc-avatar
typo

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.component.ts
> +import { AvatarSize } from '../avatar/avatar.types';
suggestion: same as above, follow our convention of type only import

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.component.ts
> +  private unsetButtonUnusedProps() {
suggestion: there is no reason to have this function, its only called in one place. Move the code in the constructor.

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.component.ts
> +    const { src, initials, size, presence, iconName, counter, isTyping } = this;
suggestion: no need for this destructuring, use this.attributename directly in the render.

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.stories.ts
> +      'disabled',
issue: those should not be in the storybook at all, use the hideControls utility

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.styles.ts
> +  :host {
issue: border radius when focused doesn't match Figma - in Figma its 4px, in yours its 20px

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.component.ts
> +    this.variant = undefined;
issue: both `role` and `type` should be hardcoded, since we don't want consumers to override the ButtonAvatar role and type for now.

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.stories.ts
> +      'soft-disabled',
issue: `role` & `type` are visible in storybook, should not be overriddable by the user - so we have to remove them.

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.stories.ts
> +};
issue: all of those button attributes are all visible in storybook still - we should remove all of them.
![image](https://github.com/user-attachments/assets/b48605d3-1dd1-46e9-9eb1-443d519b5bc9)

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/index.ts
> +import '../avatar';
issue: button needs to be registered here as well

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +    if (Object.values(AVATAR_SIZES).includes(size as AvatarSize)) {
issue: with this code we are adding logic from the avatar to the button, which is causing dependencies between them which we don't want!
solution would be: change the `setSize` method here from private to protected, keep the original implementation and then in the avatar itself do an override with super.setSize(); to call the rest.

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +import { SIZE as AVATAR_SIZES } from '../presence/presence.constants';
issue: this doesn't need to be imported and used if the way the setSize is written will be changed - see other comment

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +  @property({ type: Number }) size: PillButtonSize | IconButtonSize | AvatarSize = DEFAULTS.SIZE;
issue: setting the AvatarSize here will be an issue for consumers. When consumers use the Button Component only with Typescript, they will see that you can also pass in a "AvatarSize", which is not correct. We will mislead the consumer in the way they can use the button component.
I would need to look closer at how to fix the issue of typing here - can do that separately or maybe u can have a look?

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +    if (color) {
issue: this introduces an issue in the button now. If first the color is passed in and then the color changes to undefined, it will never be reset with the way this is written now. I know this has been done to fix Typescript issues - try to fix them directly in line 300 or so or just do `as string` etc.

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +    if (variant) {
issue: same comment as below (color) - with this code the variant attribute never gets reset to the DEFAULTS.VARIANT if no variant is passed in, after a variant has been set before.

2024-12-17 13:34 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.component.ts
> +  public static override styles: Array<CSSResult> = [...Button.styles, ...styles];
issue: since all the button styles are applied, all the `--mdc-button-` CSS Properties are also now set. None of them are necessary:
![image](https://github.com/user-attachments/assets/4ea113d2-1777-4a0d-bedc-aa920fc04667)

My suggestion to fix it is to remove the Button.styles from here and just add the focus ring styles (same as in the button) - since i think the focus ring is the only style we need.

2024-12-17 18:17 UTC, arjunkesava commented on packages/components/src/utils/mixins/AvatarComponentMixin.ts
> +  isTyping: boolean;
I've removed size from this interface.

2024-12-17 18:19 UTC, arjunkesava commented on packages/components/src/index.ts
> +  AvatarButton,
Renamed from 'ButtonAvatar' to 'AvatarButton'.

2024-12-17 18:24 UTC, arjunkesava commented on packages/components/src/components/avatarbutton/avatarbutton.component.ts
> +    this.variant = undefined as unknown as ButtonVariant;
I've removed the optional check of these properties in button component and set them to undefined using `unknown` type.

2024-12-18 07:12 UTC, arjunkesava commented on packages/components/src/components/button/button.component.ts
> +  @property({ type: Number }) size: PillButtonSize | IconButtonSize | AvatarSize = DEFAULTS.SIZE;
I've renamed the size attribute to avatarSize internally via this commit: https://github.com/momentum-design/momentum-design/pull/999/commits/690da3fdbe01dc00afe86996e84ebe18ff7f32bd

2024-12-18 08:59 UTC, cscheffauer requested changes

2024-12-18 08:59 UTC, cscheffauer commented on packages/components/src/components/avatarbutton/avatarbutton.component.ts
> +    this.type = BUTTON_DEFAULTS.TYPE;
issue: when you just open storybook for the first time, it will set a lot of default values from the button:
![image](https://github.com/user-attachments/assets/8fc67b81-f28f-4d40-b56e-3a715074a2f4)

also see that the variant and color are not undefined, like they are still there.

2024-12-18 08:59 UTC, cscheffauer commented on packages/components/src/components/buttonavatar/buttonavatar.styles.ts
> +  :host {
issue: it has now the different border radius, but the focus ring styling is broken cause of it:
![image](https://github.com/user-attachments/assets/4e87d8f3-29c4-485c-b54b-33406da1bca7)

this is how it should look like:
![image](https://github.com/user-attachments/assets/2e454c61-7c87-40aa-8fde-3a516f228279)

2024-12-18 08:59 UTC, cscheffauer commented on packages/components/src/components/button/button.component.ts
> +    if (Object.values(AVATAR_SIZES).includes(size as AvatarSize)) {
this is solved just half way - you change the private to protected, but i can't see any overrides of the setSize method in the avatarbutton nor avatar. Is this logic now removed?
if we are not intending to override the setSize method, you can keep the function private.

2024-12-18 08:59 UTC, cscheffauer commented on packages/components/src/components/avatarbutton/avatarbutton.stories.ts
> +    ]),
there is now a difference between attribute and property:
![image](https://github.com/user-attachments/assets/dc9ae276-40b2-4e4b-ba0a-70a425e05fd5)

i think we should actually rename the attribute as well, so in your component make sure the attribute and property are both "avatarSize" / "avatar-size"

2024-12-19 08:13 UTC, 2020Deeya commented on packages/components/src/utils/mixins/AvatarComponentMixin.ts
> +type Constructor<T = {}> = new (...args: any[]) => T;
Suggestion: Let's extract this 8th line from this mixin (and others including DisabledMixin and TabIndexMixin) and add it inside types.ts file.

2024-12-19 08:13 UTC, 2020Deeya commented on packages/components/src/components/avatarbutton/avatarbutton.component.ts
> +    if (Object.values(AVATAR_SIZE).includes(this.avatarSize)) {
issue: The setSize method checks if the size is a valid avatar size before deferring to the parent. However, there's a potential issue if this.avatarSize is undefined or null. This could lead to unintended behavior.

Updated one:
```
if (this.avatarSize && Object.values(AVATAR_SIZE).includes(this.avatarSize)) {
  return;
}
```

2024-12-19 08:13 UTC, 2020Deeya commented on packages/components/src/components/avatarbutton/avatarbutton.component.ts
> + *
Suggestion: Document attributes' fallback behavior. For instance: If presence or iconName are invalid or undefined is undefined, how does the avatarbutton component handle it?

2024-12-23 08:22 UTC, supminn commented
This PR will be marked closed after https://github.com/momentum-design/momentum-design/pull/1008 merges.
https://github.com/momentum-design/momentum-design/pull/1009 is the new PR reflecting the same changes.

2025-01-08 06:01 UTC, arjunkesava commented
Closing this PR as these changes were merged via https://github.com/momentum-design/momentum-design/pull/1009

2025-01-08 06:01 UTC, closed without merging